test:
  image: docker:20.10.18
  stage: build
  services:
    - name: baserow/baserow
      alias: docker
  variables:
    DOCKER_BUILDKIT: 1
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
  script:
    - docker info

