default:
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  before_script:
    - docker info

variables:
  DOCKER_BUILDKIT: 1
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"

build:
  stage: build
  script:
    - |
      cat <<EOF > Dockerfile
      FROM alpine:3.18
      RUN apk add --no-cache bash
      CMD ["echo", "Hello, World!"]
      EOF
    - docker build -t my-docker-image .
    - docker run --rm my-docker-image
