# Generated by Django 5.0.9 on 2024-11-08 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("baserow_enterprise", "0031_githubissuesdatasync"),
        ("core", "0090_exportapplicationsjob"),
    ]

    operations = [
        migrations.CreateModel(
            name="SamlAppAuthProviderModel",
            fields=[
                (
                    "appauthprovider_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.appauthprovider",
                    ),
                ),
                (
                    "metadata",
                    models.TextField(
                        blank=True,
                        help_text="The XML metadata downloaded from the metadata_url.",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="This will be set to True only after a user successfully login with this IdP. This must be True to disable normal username/password login and make SAML the only authentication provider. ",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("core.appauthprovider", models.Model),
        ),
    ]
