# Generated by Django 5.0.9 on 2024-12-26 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("baserow_enterprise", "0035_hubspotcontactsdatasync"),
        ("database", "0175_formviewfieldoptions_include_all_select_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutoDataSyncInterval",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interval",
                    models.CharField(
                        choices=[
                            ("MANUAL", "MANUAL"),
                            ("DAILY", "DAILY"),
                            ("HOURLY", "HOURLY"),
                        ],
                        default="MANUAL",
                    ),
                ),
                ("when", models.TimeField()),
                (
                    "data_sync",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="database.datasync",
                    ),
                ),
            ],
        ),
    ]
