# Generated by Django 5.0.9 on 2025-01-30 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("baserow_enterprise", "0038_localbaserowgroupedaggregaterows_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="localbaserowgroupedaggregaterows",
            name="no_group_bys_set",
            field=models.CharField(
                choices=[
                    ("GROUP_BY_ROW_ID", "Group By Row Id"),
                    ("AGGREGATE_ALL", "Aggregate All"),
                ],
                default="AGGREGATE_ALL",
                max_length=50,
            ),
        ),
    ]
