# Generated by Django 5.0.9 on 2025-02-28 03:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("baserow_enterprise", "0042_localbaserowtableserviceaggregationsortby"),
    ]

    operations = [
        migrations.AlterField(
            model_name="localbaserowtableserviceaggregationsortby",
            name="sort_on",
            field=models.CharField(
                choices=[
                    ("SERIES", "Series"),
                    ("GROUP_BY", "Group by"),
                    ("PRIMARY", "Primary"),
                ],
                max_length=255,
            ),
        ),
    ]
