# Generated by Django 5.0.9 on 2025-04-03 06:13

from django.db import migrations


def migrate_app_labels(apps, schema_editor):
    # create premium content types
    ContentType = apps.get_model("contenttypes", "ContentType")
    premium_widget_content_type = ContentType.objects.create(
        model="chartwidget", app_label="baserow_premium"
    )
    premium_service_content_type = ContentType.objects.create(
        model="localbaserowgroupedaggregaterows", app_label="baserow_premium"
    )
    ContentType.objects.create(
        model="localbaserowtableserviceaggregationgroupby",
        app_label="baserow_premium",
    )
    ContentType.objects.create(
        model="localbaserowtableserviceaggregationseries",
        app_label="baserow_premium",
    )
    ContentType.objects.create(
        model="localbaserowtableserviceaggregationsortby",
        app_label="baserow_premium",
    )

    # change foreign keys to point to premium content types
    try:
        enterprise_widget_content_type = ContentType.objects.get(
            model="chartwidget", app_label="baserow_enterprise"
        )
        enterprise_service_content_type = ContentType.objects.get(
            model="localbaserowgroupedaggregaterows", app_label="baserow_enterprise"
        )
        Widget = apps.get_model("dashboard", "Widget")
        Service = apps.get_model("core", "Service")

        Widget.objects.filter(content_type_id=enterprise_widget_content_type.id).update(
            content_type_id=premium_widget_content_type.id
        )

        Service.objects.filter(
            content_type_id=enterprise_service_content_type.id
        ).update(content_type_id=premium_service_content_type.id)
    except ContentType.DoesNotExist:
        # If migrations are applied from scratch there might not be
        # any existing entries to migrate
        pass

    # delete enterprise content types
    ContentType.objects.filter(app_label="baserow_enterprise").filter(
        model__in=[
            "chartwidget",
            "localbaserowgroupedaggregaterows",
            "localbaserowtableserviceaggregationgroupby",
            "localbaserowtableserviceaggregationseries",
            "localbaserowtableserviceaggregationsortby",
        ]
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        (
            "baserow_enterprise",
            "0043_remove_localbaserowgroupedaggregaterows_service_ptr_and_more",
        ),
        (
            "baserow_premium",
            "0025_chartwidget_localbaserowgroupedaggregaterows_and_more"
        )
    ]

    operations = [
        migrations.RunPython(migrate_app_labels),
    ]
