# Generated by Django 5.0.13 on 2025-09-16 22:39

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models

import baserow.core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("baserow_enterprise", "0052_date_dependency"),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeBaseCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "parent",
                    models.ForeignKey(
                        help_text="The parent document category, if any.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="baserow_enterprise.knowledgebasecategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="KnowledgeBaseDocument",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", baserow.core.fields.SyncedDateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        help_text="The title of the document.", max_length=250
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="A unique slug identifier for the document, used for easy reference.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        blank=True,
                        help_text="The source URL of the document, if applicable.",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("raw_document", "Raw Document"),
                            ("baserow_user_docs", "Baserow User Docs"),
                            ("faq", "FAQ"),
                            ("template", "Template"),
                        ],
                        default="raw_document",
                        max_length=20,
                    ),
                ),
                (
                    "raw_content",
                    models.TextField(
                        help_text="The raw content of the document, before any processing. This field can be automatically populated by the source_url or set manually."
                    ),
                ),
                (
                    "process_document",
                    models.BooleanField(
                        default=True,
                        help_text="Whether to process the document for ingestion or use the raw_content as-is.",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="The processed content of the document, ready for use by the AI assistant."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("processing", "Processing"),
                            ("ready", "Ready"),
                            ("stale_content", "Stale content"),
                            ("error", "Error"),
                            ("disabled", "Disabled"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="The category this document belongs to. Every document should belong to exactly one category. If not, split it in multiple documents first.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="baserow_enterprise.knowledgebasecategory",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="KnowledgeBaseChunk",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", baserow.core.fields.SyncedDateTimeField(auto_now=True)),
                (
                    "_embedding_array",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(),
                        help_text="An array containing the embedding values as a float list. This is used for as backup if pgvector is not available, so we can copy the values to the vector field when pgvector is enabled, but they cannot be queried directly.",
                        null=True,
                        size=1536,
                    ),
                ),
                (
                    "index",
                    models.PositiveIntegerField(
                        help_text="The chunk index within the document."
                    ),
                ),
                ("content", models.TextField(help_text="The content of the chunk.")),
                (
                    "metadata",
                    models.JSONField(
                        default=dict, help_text="Additional metadata about the chunk."
                    ),
                ),
                (
                    "source_document",
                    models.ForeignKey(
                        help_text="The document this chunk belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="baserow_enterprise.knowledgebasedocument",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="knowledgebasechunk",
            constraint=models.UniqueConstraint(
                fields=("source_document", "index"),
                name="unique_document_index_constraint",
            ),
        ),
    ]
