# Generated by Django 5.0.13 on 2025-09-19 20:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("baserow_enterprise", "0052_date_dependency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datedependency",
            name="dependency_buffer_type",
            field=models.CharField(
                choices=[
                    ("flexible", "Flexible"),
                    ("fixed", "Fixed"),
                    ("none", "None"),
                ],
                default="flexible",
                null=True,
            ),
        ),
    ]
