# Generated by Django 5.0.14 on 2025-09-30 09:01

import django.db.models.deletion
from django.db import migrations, models

import baserow.core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("baserow_enterprise", "0054_assistant_knowledgebase"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssistantChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", baserow.core.fields.SyncedDateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[("human", "Human"), ("ai", "AI")], max_length=10
                    ),
                ),
                ("content", models.TextField(help_text="The content of the message.")),
                (
                    "artifacts",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="A JSON field to store any additional artifacts related to the message, such as metadata or processing results.",
                    ),
                ),
                (
                    "chat",
                    models.ForeignKey(
                        help_text="The chat this message belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="baserow_enterprise.assistantchat",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["chat", "created_on"],
                        name="baserow_ent_chat_id_914682_idx",
                    )
                ],
            },
        ),
    ]
