# Generated by Django 5.2.16 on 2026-08-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("baserow_enterprise", "0063_auditlogentry_filter_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileinputelement",
            name="help_text_format",
            field=models.CharField(
                choices=[("plain", "Plain"), ("markdown", "Markdown")],
                db_default="plain",
                default="plain",
                help_text="The format of the help text.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="fileinputelement",
            name="label_format",
            field=models.CharField(
                choices=[("plain", "Plain"), ("markdown", "Markdown")],
                db_default="plain",
                default="plain",
                help_text="The format of the label.",
                max_length=10,
            ),
        ),
    ]
