# Generated by Django 5.2.16 on 2026-08-27 19:17

import baserow.core.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baserow_enterprise', '0065_auditlogentry_agent'),
        ('core', '0120_agent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentApplication',
            fields=[
                ('application_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.application')),
                ('description', models.TextField(blank=True, db_default='', help_text='What the agent should do, used to AI-configure the agent.')),
                ('active', models.BooleanField(db_default=False, default=False, help_text='Master switch: while off the agent only runs manually and its triggers never fire. Off by default so a new agent can be configured safely before going live.')),
                ('agent_identity', models.ForeignKey(blank=True, db_default=None, default=None, help_text='The workspace agent subject this application acts as. Without one the agent has no access to the workspace.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.agent')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.application',),
        ),
        migrations.CreateModel(
            name='AgentChatChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', baserow.core.fields.SyncedDateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=64)),
                ('name', models.CharField(blank=True, db_default='', max_length=160)),
                ('config', models.JSONField(blank=True, db_default={}, default=dict)),
                ('enabled', models.BooleanField(db_default=True, default=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, help_text="Unguessable token identifying this channel's inbound webhook URL.", unique=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_channels', to='baserow_enterprise.agentapplication')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='AgentChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', baserow.core.fields.SyncedDateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('title', models.CharField(blank=True, db_default='', max_length=250)),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('in_progress', 'In progress'), ('canceling', 'Canceling'), ('awaiting_approval', 'Awaiting approval'), ('error', 'Error')], db_default='idle', default='idle', max_length=20)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('trigger', 'Trigger'), ('setup', 'Setup'), ('channel', 'Channel')], db_default='manual', default='manual', max_length=20)),
                ('trigger_type', models.CharField(blank=True, db_default='', max_length=64)),
                ('event_payload', models.JSONField(blank=True, db_default=None, null=True)),
                ('channel_session_key', models.CharField(blank=True, db_default='', help_text='Channel specific session identifier (e.g. Slack channel/thread) used to continue the same conversation across messages.', max_length=255)),
                ('started_on', models.DateTimeField(blank=True, db_default=None, null=True)),
                ('completed_on', models.DateTimeField(blank=True, db_default=None, null=True)),
                ('error', models.TextField(blank=True, db_default='')),
                ('message_history', models.BinaryField(blank=True, help_text='Serialized pydantic-ai message history (JSON bytes) for multi-turn conversation context.', null=True)),
                ('total_input_tokens', models.BigIntegerField(db_default=0, default=0)),
                ('total_output_tokens', models.BigIntegerField(db_default=0, default=0)),
                ('user', models.ForeignKey(blank=True, db_default=None, default=None, help_text='The user who started the chat. Null for triggered chats.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('channel', models.ForeignKey(blank=True, db_default=None, default=None, help_text='The external chat channel this conversation belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chats', to='baserow_enterprise.agentchatchannel')),
            ],
        ),
        migrations.CreateModel(
            name='AgentChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', baserow.core.fields.SyncedDateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('human', 'Human'), ('ai', 'AI'), ('system', 'System')], max_length=10)),
                ('content', models.TextField()),
                ('artifacts', models.JSONField(blank=True, db_default={}, default=dict, help_text='Structured extras such as tool calls and reasoning.')),
                ('attachments', models.JSONField(blank=True, db_default=[], default=list, help_text='User files attached to this message, as a list of dicts with at least the stored user file `name`. The files are injected into the model prompt of the turn this message starts.')),
                ('input_tokens', models.IntegerField(blank=True, db_default=None, null=True)),
                ('output_tokens', models.IntegerField(blank=True, db_default=None, null=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='baserow_enterprise.agentchat')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='AgentDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', baserow.core.fields.SyncedDateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, db_default='')),
                ('instructions', models.TextField(blank=True, db_default='')),
                ('memory', models.TextField(blank=True, db_default='', help_text='Persistent notes loaded into every run. Written by the agent itself (e.g. ids of things it created, lessons learned) and editable by users to teach the agent.')),
                ('ai_generative_ai_type', models.CharField(blank=True, db_default=None, max_length=32, null=True)),
                ('ai_generative_ai_model', models.CharField(blank=True, db_default=None, max_length=128, null=True)),
                ('ai_temperature', models.FloatField(blank=True, db_default=None, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='baserow_enterprise.agentapplication')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='agentchat',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='baserow_enterprise.agentdefinition'),
        ),
        migrations.CreateModel(
            name='AgentTool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', baserow.core.fields.SyncedDateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=64)),
                ('name', models.CharField(blank=True, db_default='', max_length=160)),
                ('config', models.JSONField(blank=True, db_default={}, default=dict)),
                ('order', models.PositiveIntegerField(db_default=1, default=1)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='baserow_enterprise.agentdefinition')),
                ('service', models.OneToOneField(blank=True, db_default=None, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_tool', to='core.service')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='AgentTrigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', baserow.core.fields.SyncedDateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(db_default=True, default=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='baserow_enterprise.agentapplication')),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_trigger', to='core.service')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='AgentChatToolApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', baserow.core.fields.SyncedDateTimeField(auto_now=True)),
                ('tool_call_id', models.CharField(max_length=255)),
                ('tool_name', models.CharField(max_length=255)),
                ('tool_args', models.JSONField(blank=True, db_default=None, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_default='pending', default='pending', max_length=20)),
                ('decided_at', models.DateTimeField(blank=True, db_default=None, null=True)),
                ('reason', models.TextField(blank=True, db_default='', help_text='Optional rejection reason, returned to the model.')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_approvals', to='baserow_enterprise.agentchat')),
                ('decided_by', models.ForeignKey(blank=True, db_default=None, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(blank=True, db_default=None, default=None, help_text='The AI message during which the tool call was requested.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tool_approvals', to='baserow_enterprise.agentchatmessage')),
            ],
            options={
                'ordering': ('id',),
                'indexes': [models.Index(fields=['chat', 'status'], name='baserow_ent_chat_id_5b7c5e_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='agentdefinition',
            constraint=models.UniqueConstraint(fields=('application',), name='unique_agent_definition_per_application'),
        ),
        migrations.AddIndex(
            model_name='agentchat',
            index=models.Index(fields=['agent', '-updated_on'], name='baserow_ent_agent_i_87bf23_idx'),
        ),
        migrations.AddIndex(
            model_name='agentchat',
            index=models.Index(fields=['agent', 'status'], name='baserow_ent_agent_i_8c83df_idx'),
        ),
        migrations.AddIndex(
            model_name='agentchat',
            index=models.Index(fields=['channel', 'channel_session_key'], name='baserow_ent_channel_117a0e_idx'),
        ),
    ]
