# Generated by Django 5.2.17 on 2026-10-09 14:58

import django.db.models.deletion
from django.db import migrations, models

import baserow.core.fields
import baserow.core.mixins


class Migration(migrations.Migration):
    dependencies = [
        ("baserow_enterprise", "0067_graph_element"),
        ("core", "0126_alter_aiproviderconfig_api_key_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentBuilder",
            fields=[
                (
                    "application_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.application",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("core.application",),
        ),
        migrations.CreateModel(
            name="AgentDefinition",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", baserow.core.fields.SyncedDateTimeField(auto_now=True)),
                ("trashed", models.BooleanField(db_index=True, default=False)),
                ("name", models.CharField(max_length=255)),
                ("order", models.PositiveIntegerField()),
                (
                    "agent_builder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agents",
                        to="baserow_enterprise.agentbuilder",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
            },
            bases=(models.Model, baserow.core.mixins.OrderableMixin),
        ),
    ]
