# Generated by Django 5.2.14 on 2026-06-05 20:39

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RealtimeEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('channel_group', models.TextField()),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ws_realtime_events',
                'indexes': [models.Index(fields=['channel_group', 'id'], name='ws_realtime_channel_group_idx'), django.contrib.postgres.indexes.GinIndex(fields=['payload'], name='ws_realtime_payload_gin_idx', opclasses=['jsonb_path_ops'])],
            },
        ),
        # Transient replay buffer — no durability or replication needed.
        # Matched by ``UNLOGGED = True`` on the model so the read-replica
        # router keeps reads on the primary.
        migrations.RunSQL(
            sql="ALTER TABLE ws_realtime_events SET UNLOGGED;",
            reverse_sql="ALTER TABLE ws_realtime_events SET LOGGED;",
        ),
    ]
