from django.db import models

from baserow.core.formula.field import FormulaField
from baserow.core.integrations.models import Integration
from baserow.core.services.models import Service


class LMIntegration(Integration):
    """
    Integration that stores LM server configuration. Can be used for AI features.
    """

    api_key = models.TextField(
        help_text="The API key for accessing the language model service.",
    )
    model = models.CharField(
        max_length=100,
        help_text="The specific language model to use (e.g., gpt-4, llama2).",
    )
    api_base_url = models.URLField(
        null=True,
        max_length=500,
        help_text="The base URL of the language model service API.",
    )


class AiAgentService(Service):
    signature = models.TextField(
        blank=True,
        help_text="An optional signature to identify the AI agent service.",
    )
    prompt = FormulaField(
        blank=True,
        help_text="The prompt template used to guide the AI agent's responses.",
    )
    temperature = models.FloatField(
        default=0,
        help_text="The temperature setting for the language model, controlling randomness.",
    )
    max_tokens = models.IntegerField(
        default=4000,
        help_text="The maximum number of tokens to generate in the AI response.",
    )
    response = models.TextField(
        blank=True,
        help_text="The response generated by the AI agent.",
    )
