import json
from typing import Optional

import dspy
from rest_framework import serializers

from baserow.core.formula.field import FormulaField
from baserow.core.formula.serializers import FormulaSerializerField
from baserow.core.formula.validator import ensure_string
from baserow.core.services.dispatch_context import DispatchContext
from baserow.core.services.registries import DispatchTypes, ServiceType
from baserow.core.services.types import DispatchResult, FormulaToResolve, ServiceDict

from .integration_types import LMIntegrationType
from .models import AiAgentService


class AiAgentServiceType(ServiceType):
    type = "ai_agent"
    model_class = AiAgentService
    dispatch_types = [DispatchTypes.ACTION]
    integration_type = LMIntegrationType.type

    allowed_fields = [
        "integration_id",
        "signature",
        "prompt",
        "temperature",
        "max_tokens",
        "response",
    ]
    serializer_field_names = [
        "integration_id",
        "signature",
        "prompt",
        "temperature",
        "max_tokens",
        "response",
    ]

    class SerializedDict(ServiceDict):
        signature: str
        prompt: str
        temperature: float
        max_tokens: int
        response: str

    simple_formula_fields = ["prompt"]

    @property
    def serializer_field_overrides(self):
        return {
            "integration_id": serializers.IntegerField(
                required=False,
                allow_null=True,
                help_text="The id of the SMTP integration.",
            ),
            "signature": serializers.CharField(
                help_text=AiAgentService._meta.get_field("signature").help_text,
                required=False,
                allow_null=True,
                allow_blank=True,
            ),
            "prompt": FormulaSerializerField(
                help_text=AiAgentService._meta.get_field("prompt").help_text,
                required=False,
                allow_null=True,
                allow_blank=True,
            ),
        }

    def get_schema_name(self, service: AiAgentService) -> str:
        return f"ai_agent_service_{service.id}_schema"

    def generate_schema(
        self, service: AiAgentService, allowed_fields: Optional[list[str]] = None
    ) -> Optional[dict[str, any]]:
        if service.signature:
            try:
                signature = dspy.Signature(service.signature)
            except:
                pass
            else:
                return signature.model_json_schema()

        return {
            "response": {
                "type": "string",
                "description": "The response generated by the AI agent.",
                "title": "Response",
            },
        }

    def formulas_to_resolve(self, service: AiAgentService) -> list[FormulaField]:
        return super().formulas_to_resolve(service) + [
            FormulaToResolve("prompt", service.prompt, ensure_string, "prompt"),
        ]

    def dispatch_data(
        self,
        service: AiAgentService,
        resolved_values: dict[str, any],
        dispatch_context: DispatchContext,
    ) -> dict:
        if service.signature:
            signature = dspy.Signature(service.signature)
            input_values = json.loads(resolved_values["prompt"])
        else:
            signature = "question -> response"
            input_values = {"question": resolved_values["prompt"]}
        lm_integration = service.integration.specific
        lm = dspy.LM(
            api_key=lm_integration.api_key,
            model=lm_integration.model,
            temperature=service.temperature,
            max_tokens=service.max_tokens,
        )
        with dspy.context(lm=lm):
            predictor = dspy.Predict(signature)
            response = predictor(**input_values)
        return {"data": dict(response.items())}

    def dispatch_transform(
        self,
        data: any,
    ) -> DispatchResult:
        return DispatchResult(data=data["data"])
