const EnterpriseFeatures = {
  RBAC: 'RBAC',
  SSO: 'SSO',
  TEAMS: 'TEAMS',
  SUPPORT: 'SUPPORT',
  AUDIT_LOG: 'AUDIT_LOG',
  ENTERPRISE_SETTINGS: 'ENTERPRISE_SETTINGS',
  DATA_SYNC: 'DATA_SYNC',
  CHART_WIDGET: 'CHART_WIDGET',
  BUILDER_SSO: 'BUILDER_SSO',
  BUILDER_CUSTOM_CSS_JS: 'BUILDER_CUSTOM_CSS_JS',
  BUILDER_PAYMENT_ELEMENT: 'BUILDER_PAYMENT_ELEMENT',
  BUILDER_PRODUCT_SPECIALIST: 'BUILDER_PRODUCT_SPECIALIST',
}

export default EnterpriseFeatures
