# Generated by Django 5.0.9 on 2024-11-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0039_alter_page_options_page_shared"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="query_params",
            field=models.JSONField(default=dict),
        ),
    ]
