# Generated by Django 5.0.9 on 2024-12-24 07:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0042_footerelement_headerelement"),
    ]

    operations = [
        migrations.AddField(
            model_name="typographythemeconfigblock",
            name="body_font_weight",
            field=models.CharField(
                choices=[
                    ("Thin", "Thin"),
                    ("Extra-light", "Ultra Light"),
                    ("Light", "Light"),
                    ("Regular", "Regular"),
                    ("Medium", "Medium"),
                    ("Semi-bold", "Semi Bold"),
                    ("Bold", "Bold"),
                    ("Extra-bold", "Extra Bold"),
                    ("Heavy", "Heavy"),
                ],
                db_default="Regular",
                default="Regular",
                max_length=11,
            ),
        ),
        migrations.AddField(
            model_name="typographythemeconfigblock",
            name="heading_1_font_weight",
            field=models.CharField(
                choices=[
                    ("Thin", "Thin"),
                    ("Extra-light", "Ultra Light"),
                    ("Light", "Light"),
                    ("Regular", "Regular"),
                    ("Medium", "Medium"),
                    ("Semi-bold", "Semi Bold"),
                    ("Bold", "Bold"),
                    ("Extra-bold", "Extra Bold"),
                    ("Heavy", "Heavy"),
                ],
                db_default="Bold",
                default="Bold",
                max_length=11,
            ),
        ),
        migrations.AddField(
            model_name="typographythemeconfigblock",
            name="heading_2_font_weight",
            field=models.CharField(
                choices=[
                    ("Thin", "Thin"),
                    ("Extra-light", "Ultra Light"),
                    ("Light", "Light"),
                    ("Regular", "Regular"),
                    ("Medium", "Medium"),
                    ("Semi-bold", "Semi Bold"),
                    ("Bold", "Bold"),
                    ("Extra-bold", "Extra Bold"),
                    ("Heavy", "Heavy"),
                ],
                db_default="Semi-bold",
                default="Semi-bold",
                max_length=11,
            ),
        ),
        migrations.AddField(
            model_name="typographythemeconfigblock",
            name="heading_3_font_weight",
            field=models.CharField(
                choices=[
                    ("Thin", "Thin"),
                    ("Extra-light", "Ultra Light"),
                    ("Light", "Light"),
                    ("Regular", "Regular"),
                    ("Medium", "Medium"),
                    ("Semi-bold", "Semi Bold"),
                    ("Bold", "Bold"),
                    ("Extra-bold", "Extra Bold"),
                    ("Heavy", "Heavy"),
                ],
                db_default="Medium",
                default="Medium",
                max_length=11,
            ),
        ),
        migrations.AddField(
            model_name="typographythemeconfigblock",
            name="heading_4_font_weight",
            field=models.CharField(
                choices=[
                    ("Thin", "Thin"),
                    ("Extra-light", "Ultra Light"),
                    ("Light", "Light"),
                    ("Regular", "Regular"),
                    ("Medium", "Medium"),
                    ("Semi-bold", "Semi Bold"),
                    ("Bold", "Bold"),
                    ("Extra-bold", "Extra Bold"),
                    ("Heavy", "Heavy"),
                ],
                db_default="Medium",
                default="Medium",
                max_length=11,
            ),
        ),
        migrations.AddField(
            model_name="typographythemeconfigblock",
            name="heading_5_font_weight",
            field=models.CharField(
                choices=[
                    ("Thin", "Thin"),
                    ("Extra-light", "Ultra Light"),
                    ("Light", "Light"),
                    ("Regular", "Regular"),
                    ("Medium", "Medium"),
                    ("Semi-bold", "Semi Bold"),
                    ("Bold", "Bold"),
                    ("Extra-bold", "Extra Bold"),
                    ("Heavy", "Heavy"),
                ],
                db_default="Regular",
                default="Regular",
                max_length=11,
            ),
        ),
        migrations.AddField(
            model_name="typographythemeconfigblock",
            name="heading_6_font_weight",
            field=models.CharField(
                choices=[
                    ("Thin", "Thin"),
                    ("Extra-light", "Ultra Light"),
                    ("Light", "Light"),
                    ("Regular", "Regular"),
                    ("Medium", "Medium"),
                    ("Semi-bold", "Semi Bold"),
                    ("Bold", "Bold"),
                    ("Extra-bold", "Extra Bold"),
                    ("Heavy", "Heavy"),
                ],
                db_default="Regular",
                default="Regular",
                max_length=11,
            ),
        ),
    ]
