# Generated by Django 5.0.9 on 2024-12-09 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0042_footerelement_headerelement"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="query_params",
            field=models.JSONField(blank=True, default=list, db_default=[]),
        ),
    ]
