# Generated by Django 5.0.9 on 2025-01-14 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0043_page_query_params"),
    ]

    operations = [
        migrations.AddField(
            model_name="linkelement",
            name="query_parameters",
            field=models.JSONField(
                default=list,
                help_text="The query parameters for each parameter of the selected page if any.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="openpageworkflowaction",
            name="query_parameters",
            field=models.JSONField(
                default=list,
                help_text="The query parameters for each parameter of the selected page if any.",
                null=True,
            ),
        ),
    ]
