# Generated by Django 5.0.9 on 2024-12-27 06:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0044_colorthemeconfigblock_custom_colors"),
    ]

    operations = [
        migrations.AddField(
            model_name="element",
            name="style_border_radius_bottom_left",
            field=models.SmallIntegerField(
                db_default=0, default=0, help_text="Bottom-left border radius."
            ),
        ),
        migrations.AddField(
            model_name="element",
            name="style_border_radius_bottom_right",
            field=models.SmallIntegerField(
                db_default=0, default=0, help_text="Bottom-right border radius."
            ),
        ),
        migrations.AddField(
            model_name="element",
            name="style_border_radius_top_left",
            field=models.SmallIntegerField(
                db_default=0, default=0, help_text="Top-left border radius."
            ),
        ),
        migrations.AddField(
            model_name="element",
            name="style_border_radius_top_right",
            field=models.SmallIntegerField(
                db_default=0, default=0, help_text="Top-right border radius."
            ),
        ),
    ]
