# Generated by Django 5.0.9 on 2024-12-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0044_alter_typographythemeconfigblock_body_font_weight_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="buttonthemeconfigblock",
            name="button_font_weight",
            field=models.CharField(
                choices=[
                    ("Thin", "Thin"),
                    ("Extra-light", "Extra Light"),
                    ("Light", "Light"),
                    ("Regular", "Regular"),
                    ("Medium", "Medium"),
                    ("Semi-bold", "Semi Bold"),
                    ("Bold", "Bold"),
                    ("Extra-bold", "Extra Bold"),
                    ("Heavy", "Heavy"),
                    ("Black", "Black"),
                    ("Extra-black", "Extra Black"),
                ],
                db_default="Regular",
                default="Regular",
                max_length=11,
            ),
        ),
    ]
