# Generated by Django 5.0.9 on 2024-12-09 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "builder",
            "0048_alter_buttonthemeconfigblock_button_background_color_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="query_params",
            field=models.JSONField(blank=True, default=list, db_default=[]),
        ),
        migrations.AddField(
            model_name="linkelement",
            name="query_parameters",
            field=models.JSONField(
                default=list,
                db_default=[],
                help_text="The query parameters for each parameter of the selected page if any.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="openpageworkflowaction",
            name="query_parameters",
            field=models.JSONField(
                default=list,
                db_default=[],
                help_text="The query parameters for each parameter of the selected page if any.",
                null=True,
            ),
        ),
    ]
