# Generated by Django 5.0.9 on 2024-12-24 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0048_tablethemeconfigblock_table_header_font_weight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tablethemeconfigblock",
            name="table_header_font_weight",
            field=models.CharField(
                choices=[
                    ("Thin", "Thin"),
                    ("Extra-light", "Extra Light"),
                    ("Light", "Light"),
                    ("Regular", "Regular"),
                    ("Medium", "Medium"),
                    ("Semi-bold", "Semi Bold"),
                    ("Bold", "Bold"),
                    ("Extra-bold", "Extra Bold"),
                    ("Heavy", "Heavy"),
                    ("Black", "Black"),
                    ("Extra-black", "Extra Black"),
                ],
                db_default="Semi-bold",
                default="Semi-bold",
                max_length=11,
            ),
        ),
    ]
