# Generated by Django 5.0.9 on 2025-02-03 13:12

import baserow.core.formula.field
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "builder",
            "0048_alter_buttonthemeconfigblock_button_background_color_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuElement",
            fields=[
                (
                    "element_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="builder.element",
                    ),
                ),
                (
                    "orientation",
                    models.CharField(
                        choices=[
                            ("horizontal", "Horizontal"),
                            ("vertical", "Vertical"),
                        ],
                        db_default="horizontal",
                        default="horizontal",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("builder.element",),
        ),
        migrations.CreateModel(
            name="MenuElementItem",
            fields=[
                (
                    "element_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="builder.element",
                    ),
                ),
                (
                    "navigation_type",
                    models.CharField(
                        choices=[("page", "Page"), ("custom", "Custom")],
                        default="page",
                        help_text="The navigation type.",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "navigate_to_url",
                    baserow.core.formula.field.FormulaField(
                        default="",
                        help_text="If no page is selected, this indicate the destination of the link.",
                        null=True,
                    ),
                ),
                (
                    "page_parameters",
                    models.JSONField(
                        default=list,
                        help_text="The parameters for each parameters of the selected page if any.",
                        null=True,
                    ),
                ),
                (
                    "target",
                    models.CharField(
                        choices=[("self", "Self"), ("blank", "Blank")],
                        default="self",
                        help_text="The target of the link when we click on it.",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "variant",
                    models.CharField(
                        choices=[("link", "Link"), ("button", "Button")],
                        default="link",
                        help_text="The variant of the link.",
                        max_length=10,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("item", "Item"), ("separator", "Separator")],
                        default="item",
                        help_text="The type of the MenuElementItem.",
                        max_length=9,
                    ),
                ),
                ("menu_item_order", models.PositiveIntegerField()),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="builder.menuelement",
                    ),
                ),
                (
                    "navigate_to_page",
                    models.ForeignKey(
                        help_text=(
                            "Destination page id for this link. If null then we use the navigate_to_url property instead.",
                        ),
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="builder.page",
                    ),
                ),
                (
                    "parent_menu_item",
                    models.ForeignKey(
                        default=None,
                        help_text="The parent MenuElementItem element, if it is a nested item.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_item_children",
                        to="builder.menuelementitem",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("builder.element", models.Model),
        ),
    ]
