# Generated by Django 5.0.9 on 2025-02-21 07:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0051_menuitemelement_menuelement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitemelement",
            name="type",
            field=models.CharField(
                choices=[
                    ("button", "Button"),
                    ("link", "Link"),
                    ("separator", "Separator"),
                    ("spacer", "Spacer"),
                ],
                default="link",
                help_text="The type of the Menu Item.",
                max_length=9,
            ),
        ),
    ]
