# Generated by Django 5.0.9 on 2025-02-27 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0052_menuitemelement_menuelement"),
    ]

    operations = [
        migrations.AddField(
            model_name="buttonthemeconfigblock",
            name="button_active_background_color",
            field=models.CharField(
                blank=True,
                default="#4783db",
                help_text="The background color of buttons when active",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="buttonthemeconfigblock",
            name="button_active_border_color",
            field=models.CharField(
                blank=True,
                default="#275d9f",
                help_text="The border color of buttons when active",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="buttonthemeconfigblock",
            name="button_active_text_color",
            field=models.CharField(
                blank=True,
                default="#ffffffff",
                help_text="The text color of buttons when active",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="linkthemeconfigblock",
            name="link_active_text_color",
            field=models.CharField(
                blank=True,
                default="#96baf6ff",
                help_text="The hover color of links when active",
                max_length=255,
            ),
        ),
    ]
