# Generated by Django 5.0.9 on 2025-02-21 09:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0052_alter_menuitemelement_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="menuitemelement",
            old_name="menu_item_variant",
            new_name="variant",
        ),
    ]
