# Generated by Django 5.0.9 on 2025-03-10 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "builder",
            "0053_buttonthemeconfigblock_button_active_background_color_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PositionedContainerElement",
            fields=[
                (
                    "element_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="builder.element",
                    ),
                ),
                (
                    "alignment",
                    models.CharField(
                        choices=[
                            ("top", "Top"),
                            ("bottom", "Bottom"),
                            ("left_sidebar", "Left Sidebar"),
                            ("right_sidebar", "Right Sidebar"),
                        ],
                        default="top",
                        max_length=15,
                    ),
                ),
                (
                    "behaviour",
                    models.CharField(
                        choices=[("fixed", "Fixed"), ("sticky", "Sticky")],
                        default="fixed",
                        max_length=15,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("builder.element",),
        ),
    ]
