# Generated by Django 5.0.9 on 2025-02-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "builder",
            "0053_buttonthemeconfigblock_button_active_background_color_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="menuelement",
            name="alignment",
            field=models.CharField(
                choices=[("left", "Left"), ("center", "Center"), ("right", "Right")],
                default="left",
                max_length=10,
            ),
        ),
    ]
