# Generated by Django 5.0.9 on 2025-03-10 06:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0054_positionedcontainerelement"),
    ]

    operations = [
        migrations.AddField(
            model_name="positionedcontainerelement",
            name="behaviour",
            field=models.CharField(
                choices=[("fixed", "Fixed"), ("sticky", "Sticky")],
                default="fixed",
                max_length=10,
            ),
        ),
    ]
