# Generated by Django 5.0.9 on 2025-03-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0054_simplecontainerelement"),
    ]

    operations = [
        migrations.AddField(
            model_name="linkthemeconfigblock",
            name="link_active_decoration",
            field=models.CharField(
                choices=[("normal", "Normal"), ("plain", "Plain")],
                default="normal",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="linkthemeconfigblock",
            name="link_default_decoration",
            field=models.CharField(
                choices=[("normal", "Normal"), ("plain", "Plain")],
                default="normal",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="linkthemeconfigblock",
            name="link_hover_decoration",
            field=models.CharField(
                choices=[("normal", "Normal"), ("plain", "Plain")],
                default="normal",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="menuthemeconfigblock",
            name="link_active_decoration",
            field=models.CharField(
                choices=[("normal", "Normal"), ("plain", "Plain")],
                default="normal",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="menuthemeconfigblock",
            name="link_default_decoration",
            field=models.CharField(
                choices=[("normal", "Normal"), ("plain", "Plain")],
                default="normal",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="menuthemeconfigblock",
            name="link_hover_decoration",
            field=models.CharField(
                choices=[("normal", "Normal"), ("plain", "Plain")],
                default="normal",
                max_length=10,
            ),
        ),
    ]
