# Generated by Django 5.0.13 on 2025-03-26 08:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0055_linkthemeconfigblock_link_active_text_decoration_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="imagethemeconfigblock",
            name="image_border_radius",
        ),
        migrations.AddField(
            model_name="imagethemeconfigblock",
            name="image_border_radius_percent",
            field=models.SmallIntegerField(
                db_default=0,
                default=0,
                help_text="The border radius percentage for this image element.",
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Value cannot be less than 0."
                    ),
                    django.core.validators.MaxValueValidator(
                        50, message="Value cannot be greater than 50."
                    ),
                ],
            ),
        ),
        migrations.AddField(
            model_name="imagethemeconfigblock",
            name="image_border_radius_pixel",
            field=models.SmallIntegerField(
                db_default=0,
                default=0,
                help_text="The border radius pixels for this image element.",
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Value cannot be less than 0."
                    ),
                    django.core.validators.MaxValueValidator(
                        100, message="Value cannot be greater than 100."
                    ),
                ],
            ),
        ),
        migrations.AddField(
            model_name="imagethemeconfigblock",
            name="image_border_radius_type",
            field=models.CharField(
                choices=[("percent", "Percent"), ("pixel", "Pixel")],
                db_default="pixel",
                default="pixel",
                help_text="The border radius type for this image element.",
                max_length=7,
            ),
        ),
    ]
