# Generated by Django 5.0.9 on 2025-03-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0055_linkthemeconfigblock_link_active_text_decoration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="simplecontainerelement",
            name="alignment",
            field=models.CharField(
                choices=[("top", "Top"), ("bottom", "Bottom")],
                default="top",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="simplecontainerelement",
            name="behaviour",
            field=models.CharField(
                choices=[("normal", "Normal"), ("fixed", "Fixed")],
                default="normal",
                max_length=15,
            ),
        ),
    ]
