# Generated by Django 5.0.9 on 2025-04-20 17:29

from django.db import migrations, models

import baserow.contrib.builder.elements.models


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0056_ratingelement_ratinginputelement"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuelement",
            name="menu_type",
            field=models.JSONField(
                blank=True,
                default=baserow.contrib.builder.elements.models.get_default_menu_type,
                help_text="The menu type (expanded or mobile) for each device type",
                null=True,
            ),
        ),
    ]
