# Generated by Django 5.2.11 on 2026-02-11 15:28

from decimal import Decimal

from django.db import migrations, models

from baserow.contrib.builder.compat.graph_migrator import PageGraphMigrator
from baserow.core.utils import grouper


def forward(apps, schema_editor):
    Page = apps.get_model("builder", "Page")
    Element = apps.get_model("builder", "element")

    pages_iter = Page.objects.all().only("id", "graph").iterator(chunk_size=500)
    for pages in grouper(500, pages_iter):
        for page in pages:
            page_elements = Element.objects.filter(page=page).only(
                "id", "order", "parent_element_id", "place_in_container"
            )
            serialized_elements = PageGraphMigrator.serialize_page_elements(
                page_elements
            )
            page.graph = PageGraphMigrator(serialized_elements).to_graph()
        Page.objects.bulk_update(pages, ["graph"])


def reverse(apps, schema_editor):
    Page = apps.get_model("builder", "Page")
    Page.objects.update(graph={})


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0067_slackwritemessageworkflowaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="graph",
            field=models.JSONField(
                default=dict,
                help_text="A JSON serialized graph containing the points and edges.",
            ),
        ),
        migrations.RunPython(forward, reverse),
        migrations.AlterModelOptions(
            name="element",
            options={"ordering": ("id",)},
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RenameField(
                    model_name="element",
                    old_name="order",
                    new_name="compat_order",
                ),
                migrations.RenameField(
                    model_name="element",
                    old_name="place_in_container",
                    new_name="compat_place_in_container",
                ),
                migrations.RenameField(
                    model_name="element",
                    old_name="parent_element",
                    new_name="compat_parent_element",
                ),
                migrations.AlterField(
                    model_name="element",
                    name="compat_order",
                    field=models.DecimalField(
                        db_column="order",
                        decimal_places=20,
                        default=1,
                        editable=False,
                        help_text="Lowest first.",
                        max_digits=40,
                    ),
                ),
                migrations.AlterField(
                    model_name="element",
                    name="compat_parent_element",
                    field=models.ForeignKey(
                        db_column="parent_element_id",
                        default=None,
                        help_text="The parent element, if inside a container.",
                        null=True,
                        on_delete=models.CASCADE,
                        related_name="compat_children",
                        to="builder.element",
                    ),
                ),
                migrations.AlterField(
                    model_name="element",
                    name="compat_place_in_container",
                    field=models.CharField(
                        blank=True,
                        db_column="place_in_container",
                        default=None,
                        help_text="The place in the container.",
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
            # There are no database operations, we're only changing the
            # names of the fields in the model, the column names remain.
            database_operations=[],
        ),
    ]
