# Generated by Django 5.2.14 on 2026-06-03 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builder", "0068_alter_page_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="columnelement",
            name="column_widths",
            field=models.JSONField(
                default=list,
                help_text=(
                    "Custom width configuration for each column. Used when "
                    "layout_type is 'custom'."
                ),
            ),
        ),
        migrations.AddField(
            model_name="columnelement",
            name="layout_type",
            field=models.CharField(
                choices=[
                    ("auto", "Auto"),
                    ("1:2", "Ratio 1 2"),
                    ("2:1", "Ratio 2 1"),
                    ("1:3", "Ratio 1 3"),
                    ("3:1", "Ratio 3 1"),
                    ("1:1:2", "Ratio 1 1 2"),
                    ("2:1:1", "Ratio 2 1 1"),
                    ("1:2:1", "Ratio 1 2 1"),
                    ("custom", "Custom"),
                ],
                default="auto",
                help_text="The layout type determining column widths.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="columnelement",
            name="stack_on_mobile",
            field=models.BooleanField(
                default=True,
                help_text="Whether the columns should stack on mobile screens.",
            ),
        ),
    ]
