# Generated by Django 5.2.14 on 2026-06-03 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("builder", "0069_columnelement_column_widths_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="columnelement",
            name="stack_on_mobile",
        ),
    ]
