# Generated by Django 5.2.14 on 2026-06-05 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("builder", "0069_menuelement_variant"),
        ("builder", "0070_remove_columnelement_stack_on_mobile"),
    ]

    operations = []
