# Generated by Django 5.2.14 on 2026-06-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builder", "0071_merge_20260605_1126"),
    ]

    operations = [
        migrations.RenameField(
            model_name="columnelement",
            old_name="column_widths",
            new_name="column_weights",
        ),
        migrations.AlterField(
            model_name="columnelement",
            name="layout_type",
            field=models.CharField(
                choices=[
                    ("auto", "Auto"),
                    ("1:2", "Ratio 1 2"),
                    ("2:1", "Ratio 2 1"),
                    ("1:3", "Ratio 1 3"),
                    ("3:1", "Ratio 3 1"),
                    ("1:1:2", "Ratio 1 1 2"),
                    ("2:1:1", "Ratio 2 1 1"),
                    ("1:2:1", "Ratio 1 2 1"),
                    ("custom", "Custom"),
                ],
                default="auto",
                help_text="The layout type determining column weights.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="columnelement",
            name="column_weights",
            field=models.JSONField(
                default=list,
                help_text=(
                    "Custom weight configuration for each column. Used when "
                    "layout_type is 'custom'."
                ),
            ),
        ),
    ]
