# Generated by Django 5.2.14 on 2026-06-09 12:30

import baserow.contrib.builder.elements.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builder", "0072_rename_columnelement_column_widths_to_column_weights"),
    ]

    operations = [
        migrations.AddField(
            model_name="columnelement",
            name="column_stacking",
            field=models.JSONField(
                blank=True,
                db_default={
                    "desktop": "horizontal",
                    "smartphone": "stacked",
                    "tablet": "horizontal",
                },
                default=(
                    baserow.contrib.builder.elements.models.get_default_column_stacking
                ),
                help_text=(
                    "Whether columns are horizontal or stacked for each device type."
                ),
            ),
        ),
    ]
