# Generated by Django 5.2.14 on 2026-06-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0074_corestartworkflowworkflowaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="footerelement",
            name="behaviour",
            field=models.CharField(
                choices=[
                    ("normal", "Normal"),
                    ("fixed", "Fixed"),
                ],
                db_default="normal",
                default="normal",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="headerelement",
            name="behaviour",
            field=models.CharField(
                choices=[
                    ("normal", "Normal"),
                    ("fixed", "Fixed"),
                ],
                db_default="normal",
                default="normal",
                max_length=15,
            ),
        ),
    ]
