# Generated by Django 5.2.14 on 2026-07-17

from django.db import migrations, models

from baserow.contrib.builder.models import default_builder_breakpoints


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0075_container_element_positioning_behaviour"),
    ]

    operations = [
        migrations.AddField(
            model_name="builder",
            name="breakpoints",
            field=models.JSONField(
                db_default={"mobile": 500, "tablet": 768},
                default=default_builder_breakpoints,
            ),
        ),
    ]
