# Generated by Django 5.2.14 on 2026-07-17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0075_container_element_positioning_behaviour"),
    ]

    operations = [
        migrations.AddField(
            model_name="builder",
            name="mobile_breakpoint",
            field=models.IntegerField(db_default=None, default=640, null=True),
        ),
        migrations.AddField(
            model_name="builder",
            name="tablet_breakpoint",
            field=models.IntegerField(db_default=None, default=1024, null=True),
        ),
    ]
