# Generated by Django 5.2.16 on 2026-08-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0077_builder_breakpoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkboxelement',
            name='label_format',
            field=models.CharField(choices=[('plain', 'Plain'), ('markdown', 'Markdown')], db_default='plain', default='plain', help_text='The format of the label.', max_length=10),
        ),
        migrations.AddField(
            model_name='choiceelement',
            name='label_format',
            field=models.CharField(choices=[('plain', 'Plain'), ('markdown', 'Markdown')], db_default='plain', default='plain', help_text='The format of the label.', max_length=10),
        ),
        migrations.AddField(
            model_name='choiceelement',
            name='option_format',
            field=models.CharField(choices=[('plain', 'Plain'), ('markdown', 'Markdown')], db_default='plain', default='plain', help_text='The format of the option names, for both manual and formula options.', max_length=10),
        ),
        migrations.AddField(
            model_name='collectionfield',
            name='name_format',
            field=models.CharField(choices=[('plain', 'Plain'), ('markdown', 'Markdown')], db_default='plain', default='plain', help_text='The format of the field name.', max_length=10),
        ),
        migrations.AddField(
            model_name='datetimepickerelement',
            name='label_format',
            field=models.CharField(choices=[('plain', 'Plain'), ('markdown', 'Markdown')], db_default='plain', default='plain', help_text='The format of the label.', max_length=10),
        ),
        migrations.AddField(
            model_name='inputtextelement',
            name='label_format',
            field=models.CharField(choices=[('plain', 'Plain'), ('markdown', 'Markdown')], db_default='plain', default='plain', help_text='The format of the label.', max_length=10),
        ),
        migrations.AddField(
            model_name='notificationworkflowaction',
            name='description_format',
            field=models.CharField(choices=[('plain', 'Plain'), ('markdown', 'Markdown')], db_default='plain', default='plain', help_text='The format of the description.', max_length=10),
        ),
        migrations.AddField(
            model_name='notificationworkflowaction',
            name='title_format',
            field=models.CharField(choices=[('plain', 'Plain'), ('markdown', 'Markdown')], db_default='plain', default='plain', help_text='The format of the title.', max_length=10),
        ),
        migrations.AddField(
            model_name='ratinginputelement',
            name='label_format',
            field=models.CharField(choices=[('plain', 'Plain'), ('markdown', 'Markdown')], db_default='plain', default='plain', help_text='The format of the label.', max_length=10),
        ),
        migrations.AddField(
            model_name='recordselectorelement',
            name='label_format',
            field=models.CharField(choices=[('plain', 'Plain'), ('markdown', 'Markdown')], db_default='plain', default='plain', help_text='The format of the label.', max_length=10),
        ),
    ]
