# Generated by Django 5.2.16 on 2026-09-18 07:35

import baserow.core.formula.field
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0080_builderworkflowaction_trashed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choiceelementoption',
            name='name',
            field=baserow.core.formula.field.FormulaField(blank=True, default='', help_text='The display name of the option', legacy_text_mode='raw', null=True),
        ),
        migrations.AlterField(
            model_name='collectionfield',
            name='name',
            field=baserow.core.formula.field.FormulaField(blank=True, default='', help_text='The name of the field.', legacy_text_mode='raw', null=True),
        ),
        migrations.AlterField(
            model_name='textelement',
            name='format',
            field=models.CharField(choices=[('plain', 'Plain'), ('markdown', 'Markdown')], default='plain', help_text='Deprecated, use the `format` of the value instead. The format of the text.', max_length=10),
        ),
    ]
