from django.conf import settings

from baserow_premium.fields.models import GenerateAIValuesJob
from rest_framework import serializers

from baserow.core.jobs.constants import (
    JOB_CANCELLED,
    JOB_FAILED,
    JOB_FINISHED,
    JOB_PENDING,
)

VALID_JOB_STATES = [JOB_PENDING, JOB_FINISHED, JOB_FAILED, JOB_CANCELLED]


class GenerateAIFieldValueViewSerializer(serializers.Serializer):
    row_ids = serializers.ListField(
        child=serializers.IntegerField(),
        max_length=settings.BATCH_ROWS_SIZE_LIMIT,
        help_text="The ids of the rows that the values should be generated for.",
    )

    def to_internal_value(self, data):
        return super().to_internal_value(data)


class GenerateFormulaWithAIRequestSerializer(serializers.Serializer):
    ai_type = serializers.CharField(
        help_text="The AI model type that must be used when generating the formula."
    )
    ai_model = serializers.CharField(
        help_text="The AI model that must be used when generating the formula."
    )
    ai_temperature = serializers.FloatField(
        required=False,
        allow_null=True,
        min_value=0,
        max_value=2,
        help_text="Between 0 and 2, adjusts response randomness—lower values yield "
        "focused answers, while higher values increase creativity.",
    )
    ai_prompt = serializers.CharField(
        help_text="The human readable input used to generate the formula.",
        max_length=1000,
    )


class GenerateFormulaWithAIResponseSerializer(serializers.Serializer):
    formula = serializers.CharField(help_text="The formula generated by the AI.")


class GenerateAIValuesJobSerializer(serializers.ModelSerializer):
    """Serializer for GenerateAIValuesJob instances."""

    mode = serializers.ReadOnlyField(help_text="The job mode (rows, view, or table).")
    row_count = serializers.SerializerMethodField(
        help_text="Number of rows being processed (for rows mode)."
    )

    class Meta:
        model = GenerateAIValuesJob
        fields = (
            "id",
            "state",
            "progress_percentage",
            "created_on",
            "updated_on",
            "mode",
            "only_empty",
            "view_id",
            "field_id",
            "row_count",
            "row_ids",
        )
        read_only_fields = fields

    def get_row_count(self, obj):
        """Return the number of rows for rows mode."""

        if obj.row_ids:
            return len(obj.row_ids)
        return None


class ListGenerateAIValuesJobsQuerySerializer(serializers.Serializer):
    """Query parameter serializer for listing AI value generation jobs."""

    field_id = serializers.IntegerField(
        required=True,
        help_text="The AI field ID to list jobs for.",
    )
    states = serializers.CharField(
        required=False,
        help_text="Comma-separated list of job states to filter by.",
    )
    limit = serializers.IntegerField(
        required=False,
        default=7,
        min_value=1,
        max_value=100,
        help_text="Maximum number of jobs to return.",
    )

    def validate_states(self, value):
        """Validate and parse comma-separated states."""

        if not value:
            return None

        states = [s.strip() for s in value.split(",")]
        for state in states:
            if state not in VALID_JOB_STATES:
                raise serializers.ValidationError(
                    f"State '{state}' is not valid. "
                    f"Valid states are: {', '.join(VALID_JOB_STATES)}."
                )
        return states


class ListGenerateAIValuesJobsSerializer(serializers.Serializer):
    """Wrapper serializer for list of GenerateAIValuesJob instances."""

    results = GenerateAIValuesJobSerializer(many=True, read_only=True)
