from django.conf import settings

from rest_framework import serializers

from baserow_premium.fields.models import GenerateAIValuesJob


class GenerateAIFieldValueViewSerializer(serializers.Serializer):
    row_ids = serializers.ListField(
        child=serializers.IntegerField(),
        max_length=settings.BATCH_ROWS_SIZE_LIMIT,
        help_text="The ids of the rows that the values should be generated for.",
    )

    def to_internal_value(self, data):
        return super().to_internal_value(data)


class GenerateFormulaWithAIRequestSerializer(serializers.Serializer):
    ai_type = serializers.CharField(
        help_text="The AI model type that must be used when generating the formula."
    )
    ai_model = serializers.CharField(
        help_text="The AI model that must be used when generating the formula."
    )
    ai_temperature = serializers.FloatField(
        required=False,
        allow_null=True,
        min_value=0,
        max_value=2,
        help_text="Between 0 and 2, adjusts response randomness—lower values yield "
        "focused answers, while higher values increase creativity.",
    )
    ai_prompt = serializers.CharField(
        help_text="The human readable input used to generate the formula.",
        max_length=1000,
    )


class GenerateFormulaWithAIResponseSerializer(serializers.Serializer):
    formula = serializers.CharField(help_text="The formula generated by the AI.")


class GenerateAIValuesJobSerializer(serializers.ModelSerializer):
    """Serializer for GenerateAIValuesJob instances."""

    mode = serializers.ReadOnlyField(help_text="The job mode (rows, view, or table).")
    row_count = serializers.SerializerMethodField(
        help_text="Number of rows being processed (for rows mode)."
    )

    class Meta:
        model = GenerateAIValuesJob
        fields = (
            "id",
            "state",
            "progress_percentage",
            "created_on",
            "updated_on",
            "mode",
            "only_empty",
            "view_id",
            "field_id",
            "row_count",
        )
        read_only_fields = fields

    def get_row_count(self, obj):
        """Return the number of rows for rows mode."""
        if obj.row_ids:
            return len(obj.row_ids)
        return None


class ListGenerateAIValuesJobsSerializer(serializers.Serializer):
    """Wrapper serializer for list of GenerateAIValuesJob instances."""

    results = GenerateAIValuesJobSerializer(many=True, read_only=True)
