from django.urls import path

from .public_views import (
    PublicAgentChatAuthView,
    PublicAgentChatConversationsView,
    PublicAgentChatConversationView,
    PublicAgentChatMessagesView,
    PublicAgentChatView,
)
from .views import (
    AgentApplicationApprovalsView,
    AgentChatApprovalsView,
    AgentChatCancelView,
    AgentChatChannelEventsView,
    AgentChatChannelRotateSlugView,
    AgentChatChannelsView,
    AgentChatChannelView,
    AgentChatMessagesView,
    AgentChatRetryView,
    AgentChatsView,
    AgentChatView,
    AgentDefinitionView,
    AgentInstructionsDraftView,
    AgentInstructionsImproveView,
    AgentRunOnceView,
    AgentToolsView,
    AgentToolView,
    AgentTriggersView,
    AgentTriggerView,
    AgentUsageView,
    AgentWorkspaceToolsView,
    UpdateAgentDefinitionView,
)

app_name = "baserow_enterprise.api.agent_application"

urlpatterns = [
    path(
        "workspace/<int:workspace_id>/instructions/draft/",
        AgentInstructionsDraftView.as_view(),
        name="instructions_draft",
    ),
    path(
        "agents/<int:agent_id>/instructions/improve/",
        AgentInstructionsImproveView.as_view(),
        name="instructions_improve",
    ),
    path(
        "<int:application_id>/run_once/",
        AgentRunOnceView.as_view(),
        name="run_once",
    ),
    path(
        "<int:application_id>/agent/",
        AgentDefinitionView.as_view(),
        name="agent",
    ),
    path(
        "agents/<int:agent_id>/",
        UpdateAgentDefinitionView.as_view(),
        name="agent_item",
    ),
    path(
        "<int:application_id>/chats/",
        AgentChatsView.as_view(),
        name="chats",
    ),
    path(
        "<int:application_id>/chats/<uuid:chat_uuid>/messages/",
        AgentChatMessagesView.as_view(),
        name="chat_messages",
    ),
    path(
        "chats/<uuid:chat_uuid>/cancel/",
        AgentChatCancelView.as_view(),
        name="chat_cancel",
    ),
    path(
        "chats/<uuid:chat_uuid>/retry/",
        AgentChatRetryView.as_view(),
        name="chat_retry",
    ),
    path(
        "chats/<uuid:chat_uuid>/approvals/",
        AgentChatApprovalsView.as_view(),
        name="chat_approvals",
    ),
    path(
        "<int:application_id>/approvals/",
        AgentApplicationApprovalsView.as_view(),
        name="approvals",
    ),
    path(
        "<int:application_id>/workspace_tools/",
        AgentWorkspaceToolsView.as_view(),
        name="workspace_tools",
    ),
    path(
        "chats/<uuid:chat_uuid>/",
        AgentChatView.as_view(),
        name="chat_item",
    ),
    path(
        "<int:application_id>/usage/",
        AgentUsageView.as_view(),
        name="usage",
    ),
    path(
        "<int:application_id>/triggers/",
        AgentTriggersView.as_view(),
        name="triggers",
    ),
    path(
        "triggers/<int:trigger_id>/",
        AgentTriggerView.as_view(),
        name="trigger_item",
    ),
    path(
        "<int:application_id>/tools/",
        AgentToolsView.as_view(),
        name="tools",
    ),
    path(
        "tools/<int:tool_id>/",
        AgentToolView.as_view(),
        name="tool_item",
    ),
    path(
        "<int:application_id>/channels/",
        AgentChatChannelsView.as_view(),
        name="channels",
    ),
    path(
        "channels/<int:channel_id>/",
        AgentChatChannelView.as_view(),
        name="channel_item",
    ),
    path(
        "channels/<uuid:channel_uid>/events/",
        AgentChatChannelEventsView.as_view(),
        name="channel_events",
    ),
    path(
        "channels/<int:channel_id>/rotate-slug/",
        AgentChatChannelRotateSlugView.as_view(),
        name="channel_rotate_slug",
    ),
    path(
        "public/chat/<str:slug>/",
        PublicAgentChatView.as_view(),
        name="public_chat",
    ),
    path(
        "public/chat/<str:slug>/auth/",
        PublicAgentChatAuthView.as_view(),
        name="public_chat_auth",
    ),
    path(
        "public/chat/<str:slug>/conversations/",
        PublicAgentChatConversationsView.as_view(),
        name="public_chat_conversations",
    ),
    path(
        "public/chat/<str:slug>/conversations/<str:chat_uuid>/",
        PublicAgentChatConversationView.as_view(),
        name="public_chat_conversation",
    ),
    path(
        "public/chat/<str:slug>/conversations/<str:chat_uuid>/messages/",
        PublicAgentChatMessagesView.as_view(),
        name="public_chat_messages",
    ),
]
