# Generated by Django 5.0.13 on 2025-04-01 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("automation", "0002_automationworkflow"),
    ]

    operations = [
        migrations.AlterField(
            model_name="automationworkflow",
            name="automation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workflows",
                to="automation.automation",
            ),
        ),
    ]
