# Generated by Django 5.0.13 on 2025-04-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("automation", "0003_alter_automationworkflow_automation"),
    ]

    operations = [
        migrations.AddField(
            model_name="automationworkflow",
            name="order",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
