# Generated by Django 5.0.13 on 2025-04-03 08:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("automation", "0005_duplicateworkflowautomationjob"),
    ]

    operations = [
        migrations.RenameField(
            model_name="duplicateworkflowautomationjob",
            old_name="duplicated_workflow",
            new_name="duplicated_automation_workflow",
        ),
        migrations.RenameField(
            model_name="duplicateworkflowautomationjob",
            old_name="original_workflow",
            new_name="original_automation_workflow",
        ),
    ]
