# Generated by Django 5.0.13 on 2025-07-01 05:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("automation", "0009_automation_published_from_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="automationworkflow",
            name="disabled",
            field=models.BooleanField(
                default=False, help_text="Whether the published workflow is disabled."
            ),
        ),
    ]
