# Generated by Django 5.0.13 on 2025-07-01 06:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("automation", "0010_automationworkflow_disabled"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="automationworkflow",
            name="disabled",
        ),
        migrations.AddField(
            model_name="automationworkflow",
            name="paused",
            field=models.BooleanField(
                default=False, help_text="Whether the published workflow is paused."
            ),
        ),
    ]
