# Generated by Django 5.0.13 on 2025-07-01 06:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("automation", "0011_remove_automationworkflow_disabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="automationworkflow",
            name="disabled_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
