# Generated by Django 5.0.13 on 2025-07-14 11:33

import django.db.models.deletion
from django.db import migrations, models

import baserow.core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("automation", "0012_get_list_aggregate_rows_nodes"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutomationNodeHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", baserow.core.fields.SyncedDateTimeField(auto_now=True)),
                ("completed_on", models.DateTimeField(blank=True, null=True)),
                ("message", models.TextField()),
                ("is_test_run", models.BooleanField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("error", "Error"),
                            ("disabled", "Disabled"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="node_history",
                        to="automation.automationnode",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AutomationWorkflowHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", baserow.core.fields.SyncedDateTimeField(auto_now=True)),
                ("completed_on", models.DateTimeField(blank=True, null=True)),
                ("message", models.TextField()),
                ("is_test_run", models.BooleanField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("error", "Error"),
                            ("disabled", "Disabled"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_history",
                        to="automation.automationworkflow",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
