# Generated by Django 5.0.13 on 2025-08-08 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("automation", "0014_automationworkflowhistory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="automationworkflow",
            name="disabled_on",
        ),
        migrations.RemoveField(
            model_name="automationworkflow",
            name="paused",
        ),
        migrations.RemoveField(
            model_name="automationworkflow",
            name="published",
        ),
        migrations.AddField(
            model_name="automationworkflow",
            name="state",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("live", "Live"),
                    ("paused", "Paused"),
                    ("disabled", "Disabled"),
                ],
                db_default="draft",
                default="draft",
            ),
        ),
    ]
