# Generated by Django 5.0.13 on 2025-08-20 07:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("automation", "0016_corerouteractionnode"),
    ]

    operations = [
        migrations.AddField(
            model_name="localbaserowrowscreatedtriggernode",
            name="simulate_dispatch",
            field=models.BooleanField(
                default=False,
                help_text="When True, updates the sample_data of the trigger's service the next time the trigger is executed.",
            ),
        ),
        migrations.AddField(
            model_name="localbaserowrowsdeletedtriggernode",
            name="simulate_dispatch",
            field=models.BooleanField(
                default=False,
                help_text="When True, updates the sample_data of the trigger's service the next time the trigger is executed.",
            ),
        ),
        migrations.AddField(
            model_name="localbaserowrowsupdatedtriggernode",
            name="simulate_dispatch",
            field=models.BooleanField(
                default=False,
                help_text="When True, updates the sample_data of the trigger's service the next time the trigger is executed.",
            ),
        ),
    ]
