# Generated by Django 5.0.13 on 2025-08-18 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("automation", "0016_corerouteractionnode"),
        ("core", "0100_auto_20250610_1917"),
    ]

    operations = [
        migrations.CreateModel(
            name="PeriodicTriggerNode",
            fields=[
                (
                    "automationnode_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="automation.automationnode",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("automation.automationnode",),
        ),
        migrations.CreateModel(
            name="PeriodicTriggerService",
            fields=[
                (
                    "service_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.service",
                    ),
                ),
                (
                    "last_periodic_trigger",
                    models.DateTimeField(
                        help_text="Timestamp when the trigger was last executed periodically. This value is used to calculate when it should be triggered.",
                        null=True,
                    ),
                ),
                (
                    "interval",
                    models.CharField(
                        choices=[
                            ("MINUTE", "MINUTE"),
                            ("HOUR", "HOUR"),
                            ("DAY", "DAY"),
                            ("WEEK", "WEEK"),
                            ("MONTH", "MONTH"),
                        ],
                        default="MINUTE",
                        help_text="The interval frequency for triggering the automation.",
                        max_length=10,
                    ),
                ),
                (
                    "minute",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="The minute of the hour when to trigger (0-59). Required for hourly,daily, weekly, monthly intervals.",
                    ),
                ),
                (
                    "hour",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="The hour of the day when to trigger (0-23). Required for daily,weekly, monthly intervals.",
                    ),
                ),
                (
                    "day_of_week",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="The day of the week when to trigger (0=Monday, 6=Sunday). Required for weekly intervals.",
                    ),
                ),
                (
                    "day_of_month",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="The day of the month when to trigger (1-31). Required for monthly intervals.",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("core.service",),
        ),
    ]
