# Generated by Django 5.0.13 on 2025-09-04 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "automation",
            "0017_localbaserowrowscreatedtriggernode_simulate_dispatch_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="localbaserowrowscreatedtriggernode",
            name="simulate_dispatch",
        ),
        migrations.RemoveField(
            model_name="localbaserowrowsdeletedtriggernode",
            name="simulate_dispatch",
        ),
        migrations.RemoveField(
            model_name="localbaserowrowsupdatedtriggernode",
            name="simulate_dispatch",
        ),
        migrations.AddField(
            model_name="automationworkflow",
            name="simulate_until_node",
            field=models.ForeignKey(
                blank=True,
                help_text="When set, upon the next workflow run, simulates the dispatch of the workflow until this node and updates the sample_data of the node's service.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="automation.automationnode",
            ),
        ),
    ]
