# Generated by Django 5.0.13 on 2025-09-03 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("automation", "0017_remove_automationworkflow_disabled_on_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CorePeriodicTriggerNode",
            fields=[
                (
                    "automationnode_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="automation.automationnode",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("automation.automationnode",),
        ),
    ]
