# Generated by Django 5.0.14 on 2025-10-20 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("automation", "0020_corehttptriggernode"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoreIteratorActionNode",
            fields=[
                (
                    "automationnode_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="automation.automationnode",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("automation.automationnode",),
        ),
        migrations.AlterModelOptions(
            name="automationnode",
            options={"ordering": ("id",)},
        ),
        migrations.RemoveField(
            model_name="automationnode",
            name="order",
        ),
        migrations.RemoveField(
            model_name="automationnode",
            name="parent_node",
        ),
        migrations.AddField(
            model_name="automationworkflow",
            name="graph",
            field=models.JSONField(default=dict, help_text="Contains the node graph."),
        ),
    ]
