# Generated by Django 5.0.14 on 2025-10-20 15:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "automation",
            "0021_coreiteratoractionnode_alter_automationnode_options_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="automationnode",
            name="previous_node",
        ),
        migrations.RemoveField(
            model_name="automationnode",
            name="previous_node_output",
        ),
    ]
