# Generated by Django 5.0.14 on 2025-10-15 07:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("automation", "0021_coreiteratoractionnode"),
    ]

    operations = [
        migrations.AddField(
            model_name="automationworkflow",
            name="graph",
            field=models.JSONField(default=dict, help_text="Contains the node graph."),
        ),
    ]
