# Generated by Django 5.0.14 on 2025-10-16 14:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("automation", "0022_automationworkflow_graph"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="automationnode",
            options={"ordering": ("id",)},
        ),
        migrations.RemoveField(
            model_name="automationnode",
            name="order",
        ),
    ]
