# Generated by Django 5.2.11 on 2026-03-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0024_automationworkflowhistory_event_payload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationworkflowhistory',
            name='event_payload',
            field=models.JSONField(blank=True, default=None, help_text='Event payload received by the workflow.', null=True),
        ),
    ]
