# Generated by Django 5.2.12 on 2026-03-18 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0024_automationworkflowhistory_event_payload_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='automationworkflow',
            unique_together=set(),
        ),
    ]
