# Generated by Django 5.2.11 on 2026-03-04 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0025_alter_automationworkflowhistory_event_payload'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationnodehistory',
            name='is_test_run',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
