# Generated by Django 5.2.12 on 2026-03-27 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0025_automationnoderesult_iteration_path'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='automationnodehistory',
            options={'ordering': ('started_on',)},
        ),
    ]
