# Generated by Django 5.2.11 on 2026-03-04 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0026_automationnodehistory_is_test_run'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationnodehistory',
            name='is_test_run',
            field=models.BooleanField(default=False),
        ),
    ]
