# Generated by Django 5.2.12 on 2026-04-01 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0026_alter_automationworkflow_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='automationnodehistory',
            options={'ordering': ('started_on',)},
        ),
    ]
