# Generated by Django 5.2.13 on 2026-04-20 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0027_automationworkflowhistory_original_workflow_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationworkflow',
            name='state',
            field=models.CharField(choices=[('draft', 'Draft'), ('live', 'Live'), ('paused', 'Paused'), ('disabled', 'Disabled'), ('history_clone', 'History Clone')], db_default='draft', default='draft', max_length=20),
        ),
    ]
