# Generated by Django 5.2.11 on 2026-03-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0027_alter_automationnodehistory_is_test_run'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationnodehistory',
            name='is_test_run',
            field=models.BooleanField(db_default=False),
        ),
        migrations.AlterField(
            model_name='automationnoderesult',
            name='iteration',
            field=models.PositiveIntegerField(db_default=0, help_text='Keeps track of the current iteration of the Iterator node.'),
        ),
        migrations.AlterField(
            model_name='automationnoderesult',
            name='result',
            field=models.JSONField(db_default={}, help_text='Contains node results.'),
        ),
        migrations.AlterField(
            model_name='automationworkflowhistory',
            name='event_payload',
            field=models.JSONField(blank=True, db_default=None, help_text='Event payload received by the workflow.', null=True),
        ),
        migrations.AlterField(
            model_name='automationworkflowhistory',
            name='is_test_run',
            field=models.BooleanField(db_default=False, help_text='True when the workflow is being simulated.'),
        ),
    ]
