# Generated by Django 5.2.13 on 2026-04-20 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0028_alter_automationworkflow_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationworkflowhistory',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloned_workflow_histories', to='automation.automationworkflow'),
        ),
    ]
