# Generated by Django 5.2.16 on 2026-09-14 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0035_coregotoactionnode'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationworkflowhistory',
            name='triggered_by_id',
            field=models.PositiveIntegerField(help_text='The id of the subject who started this run. Null when an event started it.', null=True),
        ),
        migrations.AddField(
            model_name='automationworkflowhistory',
            name='triggered_by_name',
            field=models.CharField(blank=True, db_default='', help_text='The name of who started this run, when it started.', max_length=160),
        ),
        migrations.AddField(
            model_name='automationworkflowhistory',
            name='triggered_by_type',
            field=models.CharField(db_default='auth.User', help_text='The subject type of who started this run.', max_length=255),
        ),
    ]
