# Generated by Django 5.2.17 on 2026-10-07 08:22

import baserow.core.formula.field
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0039_coreresponseactionnode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationnode',
            name='max_retries',
            field=models.PositiveSmallIntegerField(db_default=2, default=2, help_text='How many times the node is retried after its first attempt. Only used when on_failure is retry.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='automationnode',
            name='on_failure',
            field=models.CharField(choices=[('stop', 'Stop'), ('retry', 'Retry')], db_default='stop', default='stop', help_text='What happens when this node fails: stop the run, or retry the node first.', max_length=16),
        ),
        migrations.AddField(
            model_name='automationnode',
            name='retry_condition',
            field=baserow.core.formula.field.FormulaField(blank=True, db_default='', default='', help_text="Formula evaluated against the node's result (the `current_node` data provider). When true the attempt counts as failed.", null=True),
        ),
        migrations.AddField(
            model_name='automationnode',
            name='retry_on_condition',
            field=models.BooleanField(db_default=False, default=False, help_text="Retry when retry_condition evaluates to true against the node's own result."),
        ),
        migrations.AddField(
            model_name='automationnode',
            name='retry_on_failure',
            field=models.BooleanField(db_default=True, default=True, help_text='Retry when the dispatch raises a transient error, e.g. the remote server could not be reached.'),
        ),
        migrations.AddField(
            model_name='automationnodehistory',
            name='attempt',
            field=models.PositiveSmallIntegerField(db_default=1, default=1, help_text='Which attempt of the node this entry records, starting at 1.'),
        ),
        migrations.AlterField(
            model_name='automationnodehistory',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('disabled', 'Disabled'), ('started', 'Started'), ('skipped', 'Skipped'), ('cancelled', 'Cancelled'), ('retried', 'Retried')], max_length=16),
        ),
        migrations.AlterField(
            model_name='automationworkflowhistory',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('disabled', 'Disabled'), ('started', 'Started'), ('skipped', 'Skipped'), ('cancelled', 'Cancelled'), ('retried', 'Retried')], max_length=16),
        ),
    ]
