# Generated by Django 5.2.17 on 2026-10-06 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0039_coreresponseactionnode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GmailSendEmailActionNode',
            fields=[
                ('automationnode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='automation.automationnode')),
            ],
            options={
                'abstract': False,
            },
            bases=('automation.automationnode',),
        ),
        migrations.CreateModel(
            name='GoogleCalendarCreateEventActionNode',
            fields=[
                ('automationnode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='automation.automationnode')),
            ],
            options={
                'abstract': False,
            },
            bases=('automation.automationnode',),
        ),
        migrations.CreateModel(
            name='GoogleCalendarDeleteEventActionNode',
            fields=[
                ('automationnode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='automation.automationnode')),
            ],
            options={
                'abstract': False,
            },
            bases=('automation.automationnode',),
        ),
        migrations.CreateModel(
            name='GoogleCalendarListEventsActionNode',
            fields=[
                ('automationnode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='automation.automationnode')),
            ],
            options={
                'abstract': False,
            },
            bases=('automation.automationnode',),
        ),
        migrations.CreateModel(
            name='GoogleCalendarUpdateEventActionNode',
            fields=[
                ('automationnode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='automation.automationnode')),
            ],
            options={
                'abstract': False,
            },
            bases=('automation.automationnode',),
        ),
        migrations.CreateModel(
            name='JiraCreateIssueActionNode',
            fields=[
                ('automationnode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='automation.automationnode')),
            ],
            options={
                'abstract': False,
            },
            bases=('automation.automationnode',),
        ),
        migrations.CreateModel(
            name='JiraDeleteIssueActionNode',
            fields=[
                ('automationnode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='automation.automationnode')),
            ],
            options={
                'abstract': False,
            },
            bases=('automation.automationnode',),
        ),
        migrations.CreateModel(
            name='JiraListIssuesActionNode',
            fields=[
                ('automationnode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='automation.automationnode')),
            ],
            options={
                'abstract': False,
            },
            bases=('automation.automationnode',),
        ),
        migrations.CreateModel(
            name='JiraUpdateIssueActionNode',
            fields=[
                ('automationnode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='automation.automationnode')),
            ],
            options={
                'abstract': False,
            },
            bases=('automation.automationnode',),
        ),
        migrations.CreateModel(
            name='MicrosoftTeamsSendMessageActionNode',
            fields=[
                ('automationnode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='automation.automationnode')),
            ],
            options={
                'abstract': False,
            },
            bases=('automation.automationnode',),
        ),
        migrations.CreateModel(
            name='OutlookCalendarCreateEventActionNode',
            fields=[
                ('automationnode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='automation.automationnode')),
            ],
            options={
                'abstract': False,
            },
            bases=('automation.automationnode',),
        ),
        migrations.CreateModel(
            name='OutlookCalendarDeleteEventActionNode',
            fields=[
                ('automationnode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='automation.automationnode')),
            ],
            options={
                'abstract': False,
            },
            bases=('automation.automationnode',),
        ),
        migrations.CreateModel(
            name='OutlookCalendarListEventsActionNode',
            fields=[
                ('automationnode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='automation.automationnode')),
            ],
            options={
                'abstract': False,
            },
            bases=('automation.automationnode',),
        ),
        migrations.CreateModel(
            name='OutlookCalendarUpdateEventActionNode',
            fields=[
                ('automationnode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='automation.automationnode')),
            ],
            options={
                'abstract': False,
            },
            bases=('automation.automationnode',),
        ),
        migrations.CreateModel(
            name='OutlookSendEmailActionNode',
            fields=[
                ('automationnode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='automation.automationnode')),
            ],
            options={
                'abstract': False,
            },
            bases=('automation.automationnode',),
        ),
    ]
