# Generated by Django 5.2.13 on 2026-04-30 15:20

import baserow.core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiteboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhiteboardComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', baserow.core.fields.SyncedDateTimeField(auto_now=True)),
                ('message', models.JSONField(default=dict, help_text='The rich text comment content (ProseMirror doc).')),
                ('x', models.FloatField(blank=True, help_text='Scene X coordinate of the pin (top-level comments only).', null=True)),
                ('y', models.FloatField(blank=True, help_text='Scene Y coordinate of the pin (top-level comments only).', null=True)),
                ('resolved', models.BooleanField(default=False, help_text='Top-level comments only: whether the thread is resolved.')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('mentions', models.ManyToManyField(blank=True, related_name='whiteboard_comment_mentions', to=settings.AUTH_USER_MODEL)),
                ('parent_comment', models.ForeignKey(blank=True, help_text='The thread root comment this comment replies to. Null on top-level comments.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='whiteboard.whiteboardcomment')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_whiteboard_comments', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='The user who authored the comment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whiteboard_comments', to=settings.AUTH_USER_MODEL)),
                ('whiteboard', models.ForeignKey(help_text='The whiteboard this comment belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='whiteboard.whiteboard')),
            ],
            options={
                'ordering': ('created_on',),
                'indexes': [models.Index(fields=['whiteboard', 'parent_comment', 'created_on'], name='whiteboard__whitebo_46bf16_idx')],
            },
        ),
    ]
