# Generated by Django 5.0.9 on 2025-01-30 06:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0176_remove_singleselect_missing_options"),
        ("database", "0177_airtableimportjob_skip_files"),
    ]

    operations = []
