# Generated by Django 5.0.9 on 2025-02-26 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0180_view_allow_public_export"),
    ]

    operations = [
        migrations.CreateModel(
            name="MySQLDataSync",
            fields=[
                (
                    "datasync_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="database.datasync",
                    ),
                ),
                ("mysql_host", models.CharField(max_length=255)),
                ("mysql_username", models.CharField(max_length=255)),
                ("mysql_password", models.CharField(max_length=255)),
                ("mysql_port", models.PositiveSmallIntegerField(default=3306)),
                ("mysql_database", models.CharField(max_length=255)),
                ("mysql_table", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
            bases=("database.datasync",),
        ),
    ]
