# Generated by Django 5.0.9 on 2025-02-28 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0180_view_allow_public_export"),
    ]

    operations = [
        migrations.AddField(
            model_name="viewsort",
            name="type",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Indicates the type of sort that must be applied. If empty, the default sort is used which is alphabetical in case of text. If the field type has additional sort types, you can specify them here.",
                max_length=255,
            ),
        ),
    ]
