# Generated by Django 5.0.9 on 2025-02-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0183_viewgroupby_type_viewsort_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ratingfield",
            name="style",
            field=models.CharField(
                choices=[
                    ("star", "Star"),
                    ("heart", "Heart"),
                    ("thumbs-up", "Thumbs Up"),
                    ("flag", "Flag"),
                    ("smile", "Smile"),
                ],
                default="star",
                help_text="Rating style. Allowed values: star, heart, thumbs-up, flag, smile.",
                max_length=50,
            ),
        ),
    ]
