# Generated by Django 5.0.13 on 2025-04-09 14:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0186_alter_formviewfieldoptionscondition_value_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booleanfield",
            name="boolean_default",
            field=models.BooleanField(
                default=False,
                help_text="If set, this value is going to be added every time a new row created.",
            ),
        ),
        migrations.AddField(
            model_name="datefield",
            name="date_default",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Default value of the date field. Can be a date/datetime or 'now'",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="multiplecollaboratorsfield",
            name="multiple_collaborators_default",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveBigIntegerField(),
                blank=True,
                help_text="The default value of multiple collaborators field.",
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="multipleselectfield",
            name="multiple_select_default",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveBigIntegerField(),
                blank=True,
                help_text="The default value of multiple select field.",
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="numberfield",
            name="number_default",
            field=models.DecimalField(
                blank=True,
                decimal_places=20,
                help_text="The default value of the number field.",
                max_digits=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="singleselectfield",
            name="single_select_default",
            field=models.PositiveBigIntegerField(
                blank=True,
                help_text="The default value of single select field.",
                null=True,
            ),
        ),
    ]
