# Generated by Django 5.0.13 on 2025-05-05 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0188_linkrowfield_link_row_multiple_relationships"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tableusageupdate",
            name="table",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usage_update",
                to="database.table",
            ),
        ),
    ]
