# Generated by Django 5.0.13 on 2025-05-26 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0099_mcpendpoint"),
        ("database", "0189_alter_tableusageupdate_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkspaceDatabaseSettings",
            fields=[
                (
                    "workspace",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="core.workspace",
                    ),
                ),
                ("search_table_version", models.IntegerField(default=None, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="table",
            name="search_data_state",
            field=models.CharField(
                choices=[
                    ("not_inited", "Not Inited"),
                    ("inited", "Inited"),
                    ("done", "Done"),
                    ("disabled", "Disabled"),
                ],
                default=None,
                help_text="Indicates the state of search data migration for the table, from in-table tsv columns to workspace-wide search table.",
                max_length=64,
                null=True,
            ),
        ),
    ]
