# Generated by Django 5.0.13 on 2025-06-17 12:45

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0099_mcpendpoint"),
        ("database", "0190_datasync_auto_add_new_properties"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkspaceDatabaseSettings",
            fields=[
                (
                    "workspace",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="core.workspace",
                    ),
                ),
                ("search_table_version", models.IntegerField(default=None, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="table",
            name="search_data_state",
            field=models.CharField(
                choices=[("ready", "Ready"), ("disabled", "Disabled")],
                default="ready",
                help_text="Indicates the state of search data migration for the table, from in-table tsv columns to workspace-wide search table.",
                max_length=64,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="SearchValueUpdate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "row_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(),
                        default=None,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "field_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(),
                        default=None,
                        null=True,
                        size=None,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="database.table"
                    ),
                ),
            ],
        ),
    ]
