# Generated by Django 5.0.13 on 2025-06-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0191_field_db_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="field",
            name="field_constraints",
            field=models.JSONField(
                default=list,
                help_text="List of constraints that are applied to the field.",
            ),
        ),
    ]
