# Generated by Django 5.0.13 on 2025-07-25 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0196_datasync_two_way_sync"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasync",
            name="two_way_sync_consecutive_failures",
            field=models.PositiveSmallIntegerField(
                db_default=0,
                default=0,
                help_text="Indicates the total number of two-way sync consecutive failures. Canbe used by the strategy to disable the two-way sync if needed.",
            ),
        ),
    ]
