# Generated by Django 5.2.11 on 2026-03-13 15:31

import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0204_add_row_exists_not_trashed_function'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewDefaultValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_type', models.CharField(help_text='Field type that the value is for.', max_length=255)),
                ('value', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Depends on field type.', null=True)),
                ('field', models.ForeignKey(help_text='The field to which the default value apply.', on_delete=django.db.models.deletion.CASCADE, to='database.field')),
                ('view', models.ForeignKey(help_text='The view to which the default value apply. Each view can have his own default values.', on_delete=django.db.models.deletion.CASCADE, to='database.view')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
