# Generated by Django 5.2.12 on 2026-03-26 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0206_rowhistory_database_ro_action__6ea699_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='default_values_column_added',
            preserve_default=False,
            field=models.BooleanField(
                default=False,
                help_text='Indicates whether the table has had the default_values_view_id column added.',
                null=True,
            ),
        ),
        migrations.CreateModel(
            name='ViewDefaultValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.CharField(blank=True, help_text="Optional function name (e.g. 'now') to resolve the default value dynamically at row creation time instead of using the stored value.", max_length=64, null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.field')),
                ('view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_default_values', to='database.view')),
            ],
            options={
                'ordering': ('id',),
                'unique_together': {('view', 'field')},
            },
        ),
    ]
