# Generated by Django 5.2.12 on 2026-03-26 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0207_add_view_default_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='default_values_column_added',
            field=models.BooleanField(
                default=True,
                help_text='Indicates whether the table has had the default_values_view_id column added.',
                null=True,
            ),
        ),
    ]
