# Generated by Django 5.2.13 on 2026-04-23 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0208_gridview_frozen_column_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileimportjob',
            name='importer_type',
            field=models.CharField(blank=True, default='', help_text='The importer type used to parse the file (e.g. csv, json, xml, paste).', max_length=32),
        ),
        migrations.AddField(
            model_name='fileimportjob',
            name='original_file_name',
            field=models.CharField(blank=True, default='', help_text='The original name of the uploaded file.', max_length=255),
        ),
    ]
