# Generated by Django 5.2.13 on 2026-04-21 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0208_gridview_frozen_column_count'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pendingsearchvalueupdate',
            name='pendingsearchvaluedeletion_frd',
        ),
        migrations.RemoveField(
            model_name='pendingsearchvalueupdate',
            name='table',
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE database_pendingsearchvalueupdate SET (
                    autovacuum_analyze_threshold = 2000,
                    autovacuum_analyze_scale_factor = 0.002,
                    autovacuum_vacuum_threshold = 5000,
                    autovacuum_vacuum_scale_factor = 0.01,
                    autovacuum_vacuum_insert_threshold = 5000,
                    autovacuum_vacuum_insert_scale_factor = 0.01
                );
            """,
            reverse_sql="""
                ALTER TABLE database_pendingsearchvalueupdate RESET (
                    autovacuum_analyze_threshold,
                    autovacuum_vacuum_scale_factor,
                    autovacuum_analyze_scale_factor,
                    autovacuum_vacuum_threshold,
                    autovacuum_vacuum_insert_threshold,
                    autovacuum_vacuum_insert_scale_factor
                );
            """,
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE database_pendingsearchvalueupdate
                ALTER COLUMN field_id SET STATISTICS 2000;
            """,
            reverse_sql="""
                ALTER TABLE database_pendingsearchvalueupdate
                ALTER COLUMN field_id SET STATISTICS -1;
            """,
        ),
    ]
