# Generated by Django on 2026-05-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0210_fileimportjob_importer_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="database",
            name="locked",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Indicates whether non-admins are prevented from deleting this "
                    "database."
                ),
            ),
        ),
        migrations.AddField(
            model_name="table",
            name="locked",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Indicates whether non-admins are prevented from deleting this "
                    "table."
                ),
            ),
        ),
    ]
