# Generated by Django 5.2.14 on 2026-06-29 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0211_viewsort_viewgroupby_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasync',
            name='delete_unmatched_rows',
            field=models.BooleanField(db_default=True, default=True, help_text='If enabled, rows that are no longer present in the source are deleted from the synced table on every sync. If disabled, those rows are kept and reused if the matching source row reappears.'),
        ),
    ]
