# Generated by Django 5.2.15 on 2026-07-21 10:34

import baserow.core.formula.field
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0212_data_sync_delete_unmatched_rows'),
    ]

    operations = [
        migrations.CreateModel(
            name='ButtonField',
            fields=[
                ('field_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='database.field')),
                ('label', models.CharField(blank=True, db_default='', default='', max_length=255)),
                ('url_formula', baserow.core.formula.field.FormulaField(blank=True, db_default='', default='', null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('database.field',),
        ),
    ]
