# Generated by Django 5.2.15 on 2026-07-27 20:06

import baserow.core.fields
import baserow.core.formula.field
import baserow.core.mixins
import django.db.models.deletion
from django.db import migrations, models

from baserow.contrib.database.migrations.helpers.migrate_button_url_formula_to_open_url_action import (  # noqa: E501
    migrate_button_url_formulas_to_open_url_actions,
)


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0115_ai_provider'),
        ('database', '0214_buttonfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseWorkflowAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', baserow.core.fields.SyncedDateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='database_workflow_actions', to='contenttypes.contenttype', verbose_name='content type')),
                ('field', models.ForeignKey(help_text='The button field this action belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='workflow_actions', to='database.buttonfield')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
            bases=(baserow.core.mixins.PolymorphicContentTypeMixin, models.Model, baserow.core.mixins.WithRegistry, baserow.core.mixins.OrderableMixin),
        ),
        migrations.CreateModel(
            name='OpenUrlWorkflowAction',
            fields=[
                ('databaseworkflowaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='database.databaseworkflowaction')),
                ('url', baserow.core.formula.field.FormulaField(blank=True, db_default='', default='', null=True)),
                ('target', models.CharField(choices=[('self', 'Same tab'), ('blank', 'New tab')], db_default='self', default='self', help_text='Whether the URL opens in the same tab or a new one.', max_length=10)),
            ],
            options={
                'abstract': False,
            },
            bases=('database.databaseworkflowaction',),
        ),
        migrations.CreateModel(
            name='CreateRowWorkflowAction',
            fields=[
                ('databaseworkflowaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='database.databaseworkflowaction')),
                ('service', models.ForeignKey(help_text='The service which this action is associated with.', on_delete=django.db.models.deletion.CASCADE, to='core.service')),
            ],
            options={
                'abstract': False,
            },
            bases=('database.databaseworkflowaction',),
        ),
        migrations.CreateModel(
            name='DeleteRowWorkflowAction',
            fields=[
                ('databaseworkflowaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='database.databaseworkflowaction')),
                ('service', models.ForeignKey(help_text='The service which this action is associated with.', on_delete=django.db.models.deletion.CASCADE, to='core.service')),
            ],
            options={
                'abstract': False,
            },
            bases=('database.databaseworkflowaction',),
        ),
        migrations.CreateModel(
            name='UpdateRowWorkflowAction',
            fields=[
                ('databaseworkflowaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='database.databaseworkflowaction')),
                ('service', models.ForeignKey(help_text='The service which this action is associated with.', on_delete=django.db.models.deletion.CASCADE, to='core.service')),
            ],
            options={
                'abstract': False,
            },
            bases=('database.databaseworkflowaction',),
        ),
        # Only reconciles migration state: `help_text` emits no DDL.
        migrations.AlterField(
            model_name='buttonfield',
            name='url_formula',
            field=baserow.core.formula.field.FormulaField(blank=True, db_default='', default='', help_text="Deprecated legacy field retained for compatibility. A button's URL is an `open_url` workflow action.", null=True),
        ),
        migrations.RunPython(
            migrate_button_url_formulas_to_open_url_actions,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
