# Generated by Django 5.2.16 on 2026-08-21 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0216_databaseworkflowaction_createrowworkflowaction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buttonfield',
            name='url_formula',
        ),
    ]
