# Generated by Django 5.2.16 on 2026-09-23 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0121_agent'),
        ('database', '0223_gridview_group_by_layout'),
    ]

    operations = [
        migrations.CreateModel(
            name='ButtonFieldDispatchJob',
            fields=[
                ('job_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.job')),
                ('user_websocket_id', models.CharField(help_text='The user websocket uuid needed to manage signals sent correctly.', max_length=36, null=True)),
                ('row_id', models.PositiveIntegerField(help_text='The clicked row.')),
                ('results', models.JSONField(help_text='One result per server action that ran, once the click finished.', null=True)),
                ('client_actions', models.JSONField(help_text='The frontend-only actions the browser runs after the click.', null=True)),
                ('field', models.ForeignKey(help_text='The clicked button field.', on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_jobs', to='database.buttonfield')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.job', models.Model),
        ),
    ]
