# Generated by Django 5.0.9 on 2024-12-11 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0003_widget_dashboarddatasource_summarywidget"),
    ]

    operations = [
        migrations.AlterField(
            model_name="summarywidget",
            name="data_source",
            field=models.ForeignKey(
                help_text="Data source for fetching the result to display.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="dashboard.dashboarddatasource",
            ),
        ),
    ]
