# Generated by Django 5.0.9 on 2024-12-11 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0092_alter_userprofile_language"),
        ("dashboard", "0004_alter_summarywidget_data_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dashboarddatasource",
            name="service",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dashboard_data_source",
                to="core.service",
            ),
        ),
    ]
