# Generated by Django 5.0.9 on 2024-12-11 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0005_alter_dashboarddatasource_service"),
    ]

    operations = [
        migrations.AlterField(
            model_name="summarywidget",
            name="data_source",
            field=models.ForeignKey(
                help_text="Data source for fetching the result to display.",
                on_delete=django.db.models.deletion.PROTECT,
                to="dashboard.dashboarddatasource",
            ),
        ),
    ]
