# Generated by Django 5.0.13 on 2025-05-13 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("baserow_premium", "0026_chartseriesconfig"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chartseriesconfig",
            name="widget",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="series_config",
                to="baserow_premium.chartwidget",
            ),
        ),
        migrations.AddConstraint(
            model_name="chartseriesconfig",
            constraint=models.UniqueConstraint(
                fields=("series",), name="unique_series"
            ),
        ),
    ]
