# Generated by Django 5.0.14 on 2025-10-31 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("baserow_premium", "0028_piechartwidget_piechartseriesconfig_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aifield",
            name="ai_auto_update",
            field=models.BooleanField(
                db_default=False,
                default=False,
                help_text="If set, and the prompt refers other fields, a change on those fields will trigger a recalculation of this field.",
            ),
        ),
        migrations.AddField(
            model_name="aifield",
            name="ai_auto_update_user",
            field=models.ForeignKey(
                help_text="The user on whose behalf the field is auto-updated. The user must have a licence to use AI field.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
