# Generated by Django 5.0.13 on 2025-06-26 04:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "baserow_premium",
            "0029_alter_piechartseriesconfig_series_chart_type_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="piechartseriesconfig",
            name="series_chart_type",
            field=models.CharField(
                choices=[
                    ("PIE", "Pie"),
                    ("DOUGHNUT", "Doughnut"),
                    ("POLAR_AREA", "PolarArea"),
                    ("BAR", "Bar"),
                    ("LINE", "Line"),
                ],
                default="PIE",
                help_text="Type of chart to display (Pie, Doughnut, Polar area).",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="piechartwidget",
            name="default_series_chart_type",
            field=models.CharField(
                choices=[
                    ("PIE", "Pie"),
                    ("DOUGHNUT", "Doughnut"),
                    ("POLAR_AREA", "PolarArea"),
                    ("BAR", "Bar"),
                    ("LINE", "Line"),
                ],
                db_default="PIE",
                default="PIE",
                help_text="Default chart type.",
                max_length=10,
            ),
        ),
    ]
