# Generated by Django 5.0.9 on 2025-01-24 13:44

import django.db.models.manager
from django.db import migrations

import baserow.contrib.integrations.local_baserow.models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0010_localbaserowaggregaterows"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="localbaserowtableservicefilter",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                (
                    "objects_and_without_trash",
                    baserow.contrib.integrations.local_baserow.models.LocalBaserowTableServiceRefinementManager(),
                ),
            ],
        ),
        migrations.AlterModelManagers(
            name="localbaserowtableservicesort",
            managers=[
                (
                    "objects",
                    baserow.contrib.integrations.local_baserow.models.LocalBaserowTableServiceRefinementManager(),
                ),
            ],
        ),
    ]
