# Generated by Django 5.0.13 on 2025-08-15 07:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0016_coresmtpemailservice_smtpintegration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="corehttprequestservice",
            name="response_sample",
        ),
    ]
