# Generated by Django 5.0.13 on 2025-07-23 07:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0100_auto_20250610_1917"),
        ("database", "0195_alter_pendingsearchvalueupdate_options_and_more"),
        ("integrations", "0016_coresmtpemailservice_smtpintegration"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="localbaserowdeleterow",
            index=models.Index(
                fields=["service_ptr_id"], name="integration_service_2f8c1b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="localbaserowrowscreated",
            index=models.Index(
                fields=["service_ptr_id"], name="integration_service_6f7d25_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="localbaserowrowsdeleted",
            index=models.Index(
                fields=["service_ptr_id"], name="integration_service_698998_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="localbaserowrowsupdated",
            index=models.Index(
                fields=["service_ptr_id"], name="integration_service_be8cf6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="localbaserowupsertrow",
            index=models.Index(
                fields=["service_ptr_id"], name="integration_service_a9da58_idx"
            ),
        ),
    ]
