# Generated by Django 5.0.13 on 2025-09-19 06:42

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0102_service_sample_data"),
        ("integrations", "0018_remove_corehttprequestservice_response_sample"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoreHTTPWebhookService",
            fields=[
                (
                    "service_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.service",
                    ),
                ),
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="The service identifier for the webhook.",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("core.service",),
        ),
    ]
