# Generated by Django 5.0.14 on 2025-10-08 08:49

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0105_trashentry_trash_operation_type"),
        ("integrations", "0019_coreperiodicservice"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoreHTTPTriggerService",
            fields=[
                (
                    "service_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.service",
                    ),
                ),
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="The service identifier for the webhook.",
                    ),
                ),
                ("exclude_get", models.BooleanField(default=False)),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Defines whether the service is published or not.",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("core.service",),
        ),
    ]
