# Generated by Django 5.0.13 on 2025-09-30 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0104_remove_trashentry_managed"),
        ("integrations", "0019_coreperiodicservice"),
    ]

    operations = [
        migrations.CreateModel(
            name="SlackBotIntegration",
            fields=[
                (
                    "integration_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.integration",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        help_text="The Bot User OAuth Token listed in your Slack bot's OAuth & Permissions page.",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("core.integration",),
        ),
    ]
