# Generated by Django 5.0.13 on 2025-09-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0020_corehttpwebhookservice"),
    ]

    operations = [
        migrations.AddField(
            model_name="corehttpwebhookservice",
            name="exclude_get",
            field=models.BooleanField(default=False),
        ),
    ]
