# Generated by Django 5.0.13 on 2025-09-30 14:57

import baserow.core.formula.field
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0104_remove_trashentry_managed"),
        ("integrations", "0020_slackbotintegration"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoreSlackWriteMessageService",
            fields=[
                (
                    "service_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.service",
                    ),
                ),
                (
                    "channel",
                    baserow.core.formula.field.FormulaField(
                        help_text="The Slack channel ID where the message will be sent."
                    ),
                ),
                (
                    "text",
                    baserow.core.formula.field.FormulaField(
                        help_text="The text content of the Slack message."
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("core.service",),
        ),
    ]
