# Generated by Django 5.0.13 on 2025-10-13 16:25

from django.db import migrations

import baserow.core.formula.field


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0020_corehttptriggerservice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="localbaserowaggregaterows",
            name="search_query",
            field=baserow.core.formula.field.FormulaField(
                help_text="The query to apply to the service to narrow the results down."
            ),
        ),
        migrations.AlterField(
            model_name="localbaserowgetrow",
            name="search_query",
            field=baserow.core.formula.field.FormulaField(
                help_text="The query to apply to the service to narrow the results down."
            ),
        ),
        migrations.AlterField(
            model_name="localbaserowlistrows",
            name="search_query",
            field=baserow.core.formula.field.FormulaField(
                help_text="The query to apply to the service to narrow the results down."
            ),
        ),
    ]
