# Generated by Django 5.0.14 on 2025-10-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0021_corehttpwebhookservice_exclude_get"),
    ]

    operations = [
        migrations.AddField(
            model_name="corehttpwebhookservice",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
