# Generated by Django 5.0.14 on 2025-10-20 16:43

import django.db.models.deletion
from django.db import migrations, models

import baserow.core.formula.field


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0106_schemaoperation"),
        ("integrations", "0022_coreiteratorservice"),
    ]

    operations = [
        migrations.CreateModel(
            name="AiAgentService",
            fields=[
                (
                    "service_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.service",
                    ),
                ),
                (
                    "prompt",
                    baserow.core.formula.field.FormulaField(
                        help_text="The prompt template used to guide the AI agent's responses."
                    ),
                ),
                (
                    "temperature",
                    models.FloatField(
                        default=0,
                        help_text="The temperature setting for the language model, controlling randomness.",
                    ),
                ),
                (
                    "max_tokens",
                    models.IntegerField(
                        default=4000,
                        help_text="The maximum number of tokens to generate in the AI response.",
                    ),
                ),
                (
                    "response",
                    models.TextField(
                        blank=True, help_text="The response generated by the AI agent."
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("core.service",),
        ),
        migrations.CreateModel(
            name="LMIntegration",
            fields=[
                (
                    "integration_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.integration",
                    ),
                ),
                (
                    "api_key",
                    models.TextField(
                        help_text="The API key for accessing the language model service."
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        help_text="The specific language model to use (e.g., gpt-4, llama2).",
                        max_length=100,
                    ),
                ),
                (
                    "api_base_url",
                    models.URLField(
                        help_text="The base URL of the language model service API.",
                        max_length=500,
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("core.integration",),
        ),
    ]
