# Generated by Django 5.0.14 on 2025-11-03 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0023_aiagentservice_lmintegration"),
    ]

    operations = [
        migrations.AddField(
            model_name="aiagentservice",
            name="signature",
            field=models.TextField(
                blank=True,
                help_text="An optional signature to identify the AI agent service.",
            ),
        ),
    ]
