# Generated by Django 5.2.14 on 2026-06-05 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0114_alter_workspaceinvitation_message'),
        ('database', '0211_viewsort_viewgroupby_priority'),
        ('integrations', '0027_coresmtpemailservice_use_instance_smtp_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalBaserowFieldUpdated',
            fields=[
                ('service_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.service')),
                ('field', models.ForeignKey(help_text="Only trigger when this field's value changes.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.field')),
                ('table', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.table')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.service',),
        ),
    ]
