# Generated by Django 5.0.13 on 2026-06-08 00:00

import django.db.models.deletion
from django.db import migrations, models

import baserow.core.formula.field


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0027_coresmtpemailservice_use_instance_smtp_settings"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoreCSVFileReaderService",
            fields=[
                (
                    "service_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.service",
                    ),
                ),
                (
                    "file",
                    baserow.core.formula.field.FormulaField(
                        blank=True, help_text="The CSV file to read."
                    ),
                ),
                (
                    "csv",
                    baserow.core.formula.field.FormulaField(
                        blank=True, help_text="The raw CSV data to read."
                    ),
                ),
                (
                    "input_type",
                    models.CharField(
                        choices=[("file", "File"), ("content", "Content")],
                        default="file",
                        help_text="Whether the CSV should be read from a file or raw content.",
                        max_length=32,
                    ),
                ),
                (
                    "separator",
                    models.CharField(
                        default=",",
                        help_text="The character used to separate columns in the CSV file.",
                        max_length=1,
                    ),
                ),
                (
                    "encoding",
                    models.CharField(
                        default="utf-8",
                        help_text="The character encoding used to decode the CSV file.",
                        max_length=32,
                    ),
                ),
                (
                    "first_line_is_header",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the first line of the CSV file contains column names.",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("core.service",),
        ),
    ]
