# Generated by Hermes Agent

import django.db.models.deletion
from django.db import migrations, models

import baserow.core.formula.field


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0114_alter_workspaceinvitation_message"),
        ("integrations", "0027_coresmtpemailservice_use_instance_smtp_settings"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoreCreateSnapshotService",
            fields=[
                (
                    "service_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.service",
                    ),
                ),
                (
                    "application_id",
                    models.PositiveIntegerField(
                        help_text="The ID of the application to snapshot."
                    ),
                ),
                (
                    "name",
                    baserow.core.formula.field.FormulaField(
                        blank=True,
                        default="",
                        help_text="The snapshot name. Supports formulas. Leave empty to auto-generate a name based on the application name and timestamp.",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("core.service",),
        ),
    ]
