# Generated by Django 5.2.15 on 2026-07-15 14:01

import baserow.contrib.integrations.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0114_alter_workspaceinvitation_message'),
        ('integrations', '0035_coreperiodicservice_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreInboundEmailReceiverState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_seen_message_id', models.BigIntegerField(default=0, help_text='The highest receiver-side message id that reached the webhook.')),
                ('last_deleted_message_id', models.BigIntegerField(default=0, help_text='Every message up to and including this id has been deleted from the receiver.')),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoreInboundEmailTriggerService',
            fields=[
                ('service_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.service')),
                ('token', models.CharField(db_index=True, default=baserow.contrib.integrations.core.models.generate_inbound_email_token, help_text='The localpart of the generated inbound email address.', max_length=32)),
                ('is_public', models.BooleanField(default=False, help_text='Defines whether the service is published or not.')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.service',),
        ),
    ]
