# Generated by Django 5.2.16 on 2026-09-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0036_coreinboundemailtriggerservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='smtpintegration',
            name='use_ssl',
            field=models.BooleanField(db_default=False, default=False, help_text='Whether to connect with implicit SSL/TLS, usually on port 465.'),
        ),
        migrations.AlterField(
            model_name='smtpintegration',
            name='use_tls',
            field=models.BooleanField(default=True, help_text='Whether to upgrade the connection with STARTTLS.'),
        ),
    ]
