# Generated by Django 5.0.9 on 2024-11-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0091_remove_exportapplicationsjob_exported_file_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="verify_import_signature",
            field=models.BooleanField(
                db_default=True,
                default=True,
                help_text="Indicates whether the signature of imported files should be verified.",
            ),
        ),
    ]
