# Generated by Django 5.0.13 on 2025-09-17 13:25

from django.db import migrations, models

import baserow.core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0101_trashentry_additional_restoration_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchemaOperation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", baserow.core.fields.SyncedDateTimeField(auto_now=True)),
                (
                    "table_name",
                    models.TextField(
                        help_text="The name of the database table the operation was applied to."
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        help_text="A unique identifier for the operation that was applied.",
                        max_length=64,
                    ),
                ),
            ],
            options={
                "unique_together": {("table_name", "operation")},
            },
        ),
    ]
