# Generated by Django 5.0.13 on 2025-09-17 13:32

import baserow.core.fields
import baserow.core.mixins
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0101_trashentry_additional_restoration_data"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TwoFactorAuthProviderModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", baserow.core.fields.SyncedDateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="two_factor_auth_providers",
                        to="contenttypes.contenttype",
                        verbose_name="content type",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User that setup 2fa with this provider",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="two_factor_auth_providers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                baserow.core.mixins.PolymorphicContentTypeMixin,
                baserow.core.mixins.WithRegistry,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="TOTPAuthProviderModel",
            fields=[
                (
                    "twofactorauthprovidermodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.twofactorauthprovidermodel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("core.twofactorauthprovidermodel",),
        ),
    ]
