# Generated by Django 5.0.13 on 2025-09-05 09:06

from django.db import migrations, models

import baserow.core.encoders


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0102_service_sample_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="sample_data",
            field=models.JSONField(
                blank=True,
                default=None,
                encoder=baserow.core.encoders.JSONEncoderSupportingDataClasses,
                help_text="Store the sample data used for generating a schema.",
                null=True,
            ),
        ),
    ]
