# Generated by Django 5.0.13 on 2025-09-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0102_twofactorauthprovidermodel_totpauthprovidermodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="totpauthprovidermodel",
            name="enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="totpauthprovidermodel",
            name="provisioning_url",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="totpauthprovidermodel",
            name="secret",
            field=models.CharField(
                default="", help_text="base32 secret", max_length=32
            ),
            preserve_default=False,
        ),
    ]
