# Generated by Django 5.0.13 on 2025-09-24 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0103_totpauthprovidermodel_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="totpauthprovidermodel",
            name="provisioning_qr_code",
            field=models.TextField(blank=True),
        ),
    ]
