# Generated by Django 5.0.13 on 2025-09-25 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0104_totpauthprovidermodel_provisioning_qr_code"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TwoFactorAuthRecoveryCode",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="SHA-256 hash of the recovery code", max_length=64
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User that setup 2fa with recovery codes",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="two_factor_recovery_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
