# Generated by Django 5.0.13 on 2025-09-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0104_remove_trashentry_managed"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
    ]
