# Generated by Django 5.0.14 on 2025-10-02 11:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0105_service_is_published"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="is_published",
        ),
    ]
