# Generated by Django 5.2.12 on 2026-04-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0113_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_login_ip_address',
            field=models.GenericIPAddressField(help_text='The IP address that was used on last login.', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='signup_ip_address',
            field=models.GenericIPAddressField(help_text='The IP address that was used when creating a new account.', null=True),
        ),
        migrations.AddField(
            model_name='workspaceinvitation',
            name='from_ip_address',
            field=models.GenericIPAddressField(help_text='The IP address that was used when creating the invitation.', null=True),
        ),
    ]
