# Generated by Django 5.2.13 on 2026-04-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0113_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspaceinvitation',
            name='message',
            field=models.TextField(default='', help_text='An optional message that the invitor can provide. This will be visible to the receiver of the invitation.', max_length=250),
        ),
    ]
