# Generated by Django 5.2.6 on 2026-05-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0114_alter_workspaceinvitation_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="authprovidermodel",
            name="allow_existing_users",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Whether existing user accounts with a matching email address can "
                    "sign in with this provider even if they originally used another "
                    "provider."
                ),
            ),
        ),
    ]
