# Generated by Django 5.2.15 on 2026-07-17 17:12

from django.db import migrations, models
import django.db.models.deletion

import baserow.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0114_alter_workspaceinvitation_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProviderConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', baserow.core.fields.SyncedDateTimeField(auto_now=True)),
                ('provider_type', models.CharField(max_length=32, unique=True)),
                ('api_key', models.CharField(blank=True, db_default='', default='', max_length=512)),
                ('extra_settings', models.JSONField(blank=True, db_default={}, default=dict)),
                ('is_active', models.BooleanField(db_default=True, default=True)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='AIProviderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_identifier', models.CharField(max_length=255)),
                ('is_enabled', models.BooleanField(db_default=True, default=True)),
                ('last_test_at', models.DateTimeField(blank=True, db_default=None, null=True)),
                ('last_test_status', models.CharField(blank=True, choices=[('success', 'Success'), ('failure', 'Failure')], db_default=None, max_length=16, null=True)),
                ('last_test_error', models.TextField(blank=True, db_default='', default='')),
                ('provider_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='core.aiproviderconfig')),
            ],
            options={
                'ordering': ('id',),
                'constraints': [models.UniqueConstraint(fields=('provider_config', 'model_identifier'), name='unique_ai_provider_model_identifier')],
            },
        ),
    ]
