# Generated by Django 5.2.15 on 2026-07-24 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0114_alter_workspaceinvitation_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='allow_reporting_abuse',
            field=models.BooleanField(db_default=True, default=True, help_text='Indicates whether anonymous visitors can report publicly shared resources, like views and forms, for abuse.'),
        ),
        migrations.CreateModel(
            name='AbuseReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(max_length=255)),
                ('resource_id', models.PositiveIntegerField()),
                ('resource_name', models.CharField(max_length=255)),
                ('workspace_name', models.CharField(blank=True, max_length=165)),
                ('public_url', models.TextField()),
                ('reporter_name', models.CharField(max_length=150)),
                ('reporter_email', models.EmailField(max_length=254)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('admins_notified', models.BooleanField(db_default=False, default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.workspace')),
            ],
            options={
                'ordering': ['-created_on'],
                'indexes': [models.Index(fields=['resource_type', 'resource_id', 'created_on'], name='core_abuser_resourc_f4a22d_idx')],
            },
        ),
    ]
