# Generated by Django 5.2.15 on 2026-07-22 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0115_ai_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProviderWorkspaceOverride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='aiproviderconfig',
            name='workspace',
            field=models.ForeignKey(blank=True, db_default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_provider_configs', to='core.workspace'),
        ),
        migrations.AlterField(
            model_name='aiproviderconfig',
            name='provider_type',
            field=models.CharField(max_length=32),
        ),
        migrations.AddConstraint(
            model_name='aiproviderconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('workspace__isnull', True)), fields=('provider_type',), name='unique_instance_ai_provider_type'),
        ),
        migrations.AddConstraint(
            model_name='aiproviderconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('workspace__isnull', False)), fields=('workspace', 'provider_type'), name='unique_workspace_ai_provider_type'),
        ),
        migrations.AddField(
            model_name='aiproviderworkspaceoverride',
            name='provider_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_overrides', to='core.aiproviderconfig'),
        ),
        migrations.AddField(
            model_name='aiproviderworkspaceoverride',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_provider_overrides', to='core.workspace'),
        ),
        migrations.AddConstraint(
            model_name='aiproviderworkspaceoverride',
            constraint=models.UniqueConstraint(fields=('workspace', 'provider_config'), name='unique_workspace_ai_provider_override'),
        ),
    ]
