# Generated by Django 5.2.15 on 2026-08-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0116_abuse_report_and_allow_reporting_abuse'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='error_code',
            field=models.CharField(blank=True, db_default='', default='', help_text='A machine readable error code indicating why the job failed.', max_length=128),
        ),
    ]
