# Generated by Django 5.2 on 2026-07-27

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import F
from django.db.models.functions import JSONObject

import baserow.core.ai_provider.models


def initialize_existing_model_test_capabilities(apps, schema_editor):
    AIProviderModel = apps.get_model("core", "AIProviderModel")
    AIProviderModel.objects.exclude(last_test_status__isnull=True).update(
        last_test_capabilities=JSONObject(
            text=JSONObject(status=F("last_test_status"), error=F("last_test_error"))
        )
    )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0118_aiproviderworkspaceoverride_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aiprovidermodel",
            name="feature_types",
            field=models.JSONField(
                blank=True,
                db_default=["ai_fields"],
                default=(
                    baserow.core.ai_provider.models.get_default_ai_provider_model_feature_types
                ),
                help_text=(
                    "The AI features allowed to select this model. This controls "
                    "eligibility, not which features currently use the model."
                ),
            ),
        ),
        migrations.AddField(
            model_name="aiprovidermodel",
            name="last_test_capabilities",
            field=models.JSONField(
                blank=True,
                db_default={},
                default=dict,
                help_text=(
                    "The reusable capability results from the last model test. "
                    "Feature results are derived from these values."
                ),
            ),
        ),
        migrations.RunPython(
            initialize_existing_model_test_capabilities,
            migrations.RunPython.noop,
        ),
        migrations.CreateModel(
            name="AIProviderFeatureSetting",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feature_type",
                    models.CharField(
                        db_default="",
                        help_text=(
                            "The AI feature whose scoped default-model selection "
                            "this setting controls."
                        ),
                        max_length=64,
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        db_default=True,
                        default=True,
                        help_text=(
                            "Whether this feature uses the selected model at this "
                            "scope. False represents an explicit disable and requires "
                            "the model to be null."
                        ),
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        blank=True,
                        db_default=None,
                        help_text=(
                            "The model actually selected for this feature at this "
                            "scope. The model must also list the feature in its "
                            "feature availability."
                        ),
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="feature_settings",
                        to="core.aiprovidermodel",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        blank=True,
                        db_default=None,
                        help_text=(
                            "The workspace this selection applies to. Null means "
                            "instance-wide; the absence of a workspace setting means "
                            "inherit the instance selection."
                        ),
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_provider_feature_settings",
                        to="core.workspace",
                    ),
                ),
            ],
            options={"ordering": ("id",)},
        ),
        migrations.AddConstraint(
            model_name="aiproviderfeaturesetting",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(("is_enabled", False), ("model__isnull", True))
                    | models.Q(("is_enabled", True), ("model__isnull", False))
                ),
                name="valid_ai_provider_feature_setting_model",
            ),
        ),
        migrations.AddConstraint(
            model_name="aiproviderfeaturesetting",
            constraint=models.UniqueConstraint(
                condition=models.Q(("workspace__isnull", True)),
                fields=("feature_type",),
                name="unique_instance_ai_provider_feature_setting",
            ),
        ),
        migrations.AddConstraint(
            model_name="aiproviderfeaturesetting",
            constraint=models.UniqueConstraint(
                condition=models.Q(("workspace__isnull", False)),
                fields=("workspace", "feature_type"),
                name="unique_workspace_ai_provider_feature_setting",
            ),
        ),
    ]
