# Generated by Django 5.2.16 on 2026-09-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0125_import_legacy_ai_provider_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiproviderconfig',
            name='api_key',
            field=models.CharField(blank=True, db_default='', default='', max_length=4096),
        ),
    ]
