# Generated by Django 5.2.17 on 2026-10-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0126_alter_aiproviderconfig_api_key_max_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="template_type",
            field=models.CharField(
                choices=[("official", "Official"), ("user", "User")],
                db_default="official",
                default="official",
                help_text="Official templates are synced from the repository, user templates are created by users. Set on create, never changed.",
                max_length=16,
            ),
        ),
    ]
