# Generated by Django 5.2.17 on 2026-10-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0126_alter_aiproviderconfig_api_key_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcpendpoint',
            name='allowed_tools',
            field=models.JSONField(blank=True, default=None, help_text='Names of the MCP tools this endpoint may use. Null allows every enabled tool.', null=True),
        ),
        migrations.AddField(
            model_name='mcpendpoint',
            name='oauth_client_id',
            field=models.CharField(blank=True, db_index=True, help_text='The OAuth client this endpoint was created for by consent. Null for endpoints created by the user.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="mcpendpoint",
            name="key",
            field=models.CharField(
                max_length=32,
                unique=True,
                db_index=True,
                null=True,
                blank=True,
                help_text="The unique endpoint key that can be used to authorize for "
                "the MCP service. Null for OAuth grants, which only accept their "
                "access tokens.",
            ),
        ),
        migrations.AddConstraint(
            model_name="mcpendpoint",
            constraint=models.UniqueConstraint(
                fields=["user", "workspace", "oauth_client_id"],
                condition=models.Q(oauth_client_id__isnull=False),
                name="mcp_endpoint_unique_oauth_grant",
            ),
        ),
    ]
