# Generated by Django 5.2.17 on 2026-10-06 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0126_alter_aiproviderconfig_api_key_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcpendpoint',
            name='allowed_tools',
            field=models.JSONField(blank=True, default=None, help_text='Names of the MCP tools this endpoint may use. Null allows every enabled tool.', null=True),
        ),
    ]
