# Generated by Django 5.2.17 on 2026-10-06 10:03

import django.db.models.deletion
import django.db.models.functions.datetime
import django.db.models.manager
from django.conf import settings
from django.contrib.postgres.operations import AddConstraintNotValid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0126_alter_aiproviderconfig_api_key_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TemplateLinkAccess",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelManagers(
            name="template",
            managers=[
                ("objects_and_trash", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="template",
            name="author",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who created the template. Null for official templates.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="authored_templates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True, db_default=django.db.models.functions.datetime.Now()
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="description",
            field=models.TextField(
                blank=True,
                db_default="",
                default="",
                help_text="The description shown in the template browser.",
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="install_count",
            field=models.PositiveIntegerField(
                db_default=0,
                default=0,
                help_text="How many times the template has been installed.",
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="last_updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Who last changed the details or content of the template.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="listing_state",
            field=models.CharField(
                choices=[
                    ("private", "Private"),
                    ("pending", "Pending"),
                    ("public", "Public"),
                    ("rejected", "Rejected"),
                    ("blocked", "Blocked"),
                ],
                db_default="public",
                default="public",
                help_text="Who can find the template in the template browser.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="marked_for_deletion_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When set, the template is unavailable and will be removed later.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="private_link_token",
            field=models.CharField(
                blank=True,
                help_text="The token of the private link. Null when the template has no private link.",
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="state_before_block",
            field=models.CharField(
                blank=True,
                choices=[
                    ("private", "Private"),
                    ("pending", "Pending"),
                    ("public", "Public"),
                    ("rejected", "Rejected"),
                ],
                help_text="The listing state the template returns to when it is unblocked.",
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="state_changed_at",
            field=models.DateTimeField(
                blank=True, help_text="When the listing state last changed.", null=True
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="state_changed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Who last changed the listing state.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="state_note",
            field=models.TextField(
                blank=True,
                db_default="",
                default="",
                help_text="The reason given with the last listing state change, for example when rejecting or blocking.",
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="template_type",
            field=models.CharField(
                choices=[("official", "Official"), ("user", "User")],
                db_default="official",
                default="official",
                help_text="Official templates are synced from the repository, user templates are created by users. Set on create, never changed.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="updated_on",
            field=models.DateTimeField(
                auto_now=True, db_default=django.db.models.functions.datetime.Now()
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="uuid",
            field=models.UUIDField(
                editable=False,
                help_text="Stable identifier of the template. Official templates derive it from their slug, so it is the same on every instance.",
                null=True,
                unique=True,
            ),
        ),
        # Added NOT VALID so adding it takes no long lock; validated in 0128.
        AddConstraintNotValid(
            model_name="template",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("template_type", "user"), _negated=True),
                    ("author__isnull", False),
                    _connector="OR",
                ),
                name="template_user_type_requires_author",
            ),
        ),
        migrations.AddField(
            model_name="templatelinkaccess",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="link_accesses",
                to="core.template",
            ),
        ),
        migrations.AddField(
            model_name="templatelinkaccess",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="template_link_accesses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="templatelinkaccess",
            constraint=models.UniqueConstraint(
                fields=("template", "user"), name="unique_template_link_access"
            ),
        ),
    ]
